### ISSUE TITLE
help page has incorrect documentation for font name option

### ISSUE THREAD

**Issue by themonstermash** [bartreardon/swiftDialog#104]
/usr/local/bin/dialog --help shows the option to change font face as "font=<fontname>" but the actual option appears to be name=<fontname>

This is properly documented in the wiki here: https://github.com/bartreardon/swiftDialog/wiki/Customising-the-Title

**Comment by bartreardon** [comment]
Thanks - this was reported earlier and is corrected on 1.10.1
