### ISSUE TITLE
How to update list items, including status text and status icon when initiated via json

### ISSUE THREAD

**Issue by mm2270** [bartreardon/swiftDialog#106]
Hi. I just started playing a bit with swiftDialog. I'm interested in using the list items, and in my testing with it, I'm confused about how to use the json source format to initially set up the list, but then update those items dynamically in the dialog, including BOTH the status text and the icon (wait, pending, successful, fail, etc.)

I see we can echo into the command file, but when trying this, I can only ever seem to update the icon OR the status text, not both. No matter what format I use it only accepts the last item in the string and ignores the other. And when doing this, it ends up removing whichever one it ignored, so for example, my status text vanishes, but the icon gets updated. Or, the icon vanishes and the status text updates.

If I'm supposed to use another json file to update this list, then I'm not clear how to do that. I may have missed it, but I didn't see anything in the documentation describing how to do that.

If this just isn't possible because JSON config is considered an advanced setup option, is there any plan to add the capability to update those in full in a future version?

I hope what I'm describing makes sense, but if there is no more info needed I'm happy to provide that.

**Comment by acodega** [comment]
JSON or not, you would update the Dialog window in the same way. Also, you would want to enter update by itself. They basically happen fast enough that no delay noticed on screen. For example, when my installer script finishes I update the Dialog window this way:

`dialog_command "progresstext: Install of Microsoft Office complete"
dialog_command "progress: complete"
dialog_command "button1text: Done"
dialog_command "button1: enable" `

**Comment by bartreardon** [comment]
What @acodega said. There's some documentation on how the command file works here https://github.com/bartreardon/swiftDialog/wiki/Updating-Dialog-with-new-content--(v1.9.0) but basically you echo the command you want to run (i.e. the item you want to change) one line at a time. 

swiftDialog will clear the command file at the beginning of every run, so you can't pre-load it with instructions.

**Comment by mm2270** [comment]
Hmm, ok. Thanks for the replies. Maybe I'm misunderstanding, but even when I try it the way it's being described, in the list items, I can only seem to get _either_ the icon updated or the status text updated. I can't keep both present in the dialog window when I update the command file one line at a time. Yet, I _can_ configure the JSON file to include both a status text and status icon when initializing the dialog. For example, a line might look like this to start:

![image](https://user-images.githubusercontent.com/3653600/163882856-2dfd9cac-a09d-4b3b-b38b-baf024c11f36.png)

But once I push any updates to the command file, even if I separate them out into 2 discrete commands, I can't update both that status and icon together. It seems to be one or the other.

Am I missing something still?

**Comment by bartreardon** [comment]
so to update your line to say indicate success of the Google Chrome item run:
 `echo "statustext: title: Google Chrome, status: success, statustext: Install Completed`
 
 the `title:` `status:` and `statustext:` keywords are separated with a comma. `title` is used to locate the line you want to change so it needs to be exact, or if you know it's position in the list you can use `index: <int>` instead, for example `index: 0, status: success, statustext: Install Completed` if it was the first item in the list (indexes start at 0)

**Comment by mm2270** [comment]
Ah, got it now! Thanks a lot for that explanation and example. That’s very helpful!

I feel like I had tried putting commas between the items but I must have been missing a comma or had them in the wrong location or something which was messing it up for me. 

Thanks!

**Comment by bartreardon** [comment]
the command parser is pretty lenient with malformed input - if it doesn't know what it's looking at it'll just ignore it. Might think about re-doing the debug mode so it will report what it saw and what it thinks it should do with it to make testing easier.
