### ISSUE TITLE
Support for two (or more) columns of checkboxes

### ISSUE THREAD

**Issue by joncrain** [bartreardon/swiftDialog#108]
It would be great to be able to handle more checkboxes without the need to scroll:
![150663608-6ee03207-0558-4769-a016-44fe5822fccb](https://user-images.githubusercontent.com/5123982/164058533-95036c0b-2b4e-4e80-a7af-ee8a2eca18d1.png)

**Comment by bartreardon** [comment]
Good suggestion. What would the order of the checkboxes look like?

Option 1: 
![image](https://user-images.githubusercontent.com/3598965/164087733-34f420aa-cc05-4dcc-95dd-d857fbb506d3.png)

Option 2:
![image](https://user-images.githubusercontent.com/3598965/164087853-13b2efa7-6794-41ab-bb55-b72362c47097.png)

**Comment by joncrain** [comment]
I prefer option 2.

**Comment by smithjw** [comment]
Bump: _cough v2.2.0 cough_

**Comment by bartreardon** [comment]
For those playing at home, I have some test code working for this - needs some tinkering to work out the implementation details and what, if any, influence you as an admin would have over the layout.

![image](https://user-images.githubusercontent.com/3598965/216486630-56acd45e-c678-4d12-9cea-e477e7e35e99.png)

**Comment by bartreardon** [comment]
Semi related - playing with allowing swapping checkboxes for switch style

<img width="612" alt="image" src="https://user-images.githubusercontent.com/3598965/233079753-290ce22f-5726-4333-9361-a1370dfcbfdc.png">

**Comment by bartreardon** [comment]
Closing this as a "wontfix"

Rather than multiple columns of checkboxes, using the `switch` style to allow an arbitrary list of items in a scrollview will be the recommended method for managing bulk selectable options. 

Some enhancements in [2.3](https://github.com/bartreardon/swiftDialog/releases/tag/v2.3.0) helps with presentation and performance.
