### ISSUE TITLE
FR: Ability to map the Quit command to a different key combo

### ISSUE THREAD

**Issue by mm2270** [bartreardon/swiftDialog#111]
I'd like the ability to make it so a dialog does not quit when pressing Command + Q on the keyboard.

Background: I'm working on moving my automated device enrollment workflow over from DEPNotify to swiftDialog, but one thing DEPNotify can do which I'm missing is the ability to map the quit command to a unique key combo. This prevents someone from accidentally (or purposefully) quitting the dialog. Right now dialog responds to Command + Q even if the main button is disabled. The script continues to run in the background, but could be very confusing for the end user if there is no window on screen displaying what's happening.

**Comment by bartreardon** [comment]
I've had a few comments about the availability of cmd+Q.

I personally think there should always be a way to quit dialog, specifically for instances when the controlling script goes south and you have a full screen (or blurred background) dialog hogging the UI making the device unusable. 

Setting a custom quit hotkey might be an acceptable compromise though.

**Comment by mm2270** [comment]
Yes, completely agreed! I wouldn't want a way that dialog could NOT be quit, exactly for the reasons you mentioned. Just a way to map the quit command to another key combo.

**Comment by dan-snelson** [comment]
+1

**Comment by bartreardon** [comment]
https://github.com/bartreardon/swiftDialog/commit/262eb7e83f568700bb245e4019d006123d855f1e should address this. Adds `--quitkey` so you can set it to something else like `--quitkey x`
As a bonus, blocking cmd+w as well
If someone does `cmd+q` quit then the exit code will be `10` so it's detectable. 

a change where I cleaned up some of the markdown stuff snuck in as well and I couldn't be bothered cleaning out the commits to make it a seperate feature branch.

**Comment by bartreardon** [comment]
https://github.com/bartreardon/swiftDialog/wiki/Modifying-command-q-behaviour

**Comment by mm2270** [comment]
Awesome! Thanks for doing this. Tested and working great!
