### ISSUE TITLE
Providing 'selectvalues' via json file for a drop down does not show values

### ISSUE THREAD

**Issue by kdrwygvh** [bartreardon/swiftDialog#112]
Using Dialog 1.10.1, adding a list of choices to a drop down via 'selectvalues' in a json file yields a blank drop down list. The same json file works with previous versions of Dialog.

**Comment by bartreardon** [comment]
Can you post an example? Possible when i made the update that allows multiple select values i might have nuked the previous way it worked (which i try to not do). In the meantime, the json as described in the wiki should work https://github.com/bartreardon/swiftDialog/wiki/Selectable-Lists#json-format

**Comment by kdrwygvh** [comment]
The new method does work for me. Example of previous method (just a single drop down) 
`"selecttitle": "Country","selectvalues": [ "Argentina","Aruba"]`

**Comment by bartreardon** [comment]
I'll take a look in any case. I don't like to make changes that break existing workflows if I can help it so if I update how something is configured, I try to keep the way it worked previously.
