### ISSUE TITLE
Some keys not working with 1.10.2-2573

### ISSUE THREAD

**Issue by pasmaano** [bartreardon/swiftDialog#116]
When I try to enter text to textfields, keys **n, m, q** and **w** doesn't work. Nothing happens, except when I press **q** it quits Dialog app. Just pressing q, no need for cmd + q. I had not configured the new `--quitkey` command. 

I downgraded to 1.10.1-2569 and there all keys work normally. 

Could you look into this if you can replicate it yourself?

**Comment by bartreardon** [comment]
hmm - correct. It should only be pulling these keys when `command` is also pressed. will look at this now.

**Comment by smilieK** [comment]
Noticed the same thing using a password field. No matter the password on a machine would not work if typed. If copied and pasted it worked. After wasting each key be typed. Looks like it does not recognize the "w" key in latest version.

**Comment by bartreardon** [comment]
https://github.com/bartreardon/swiftDialog/releases/tag/v1.10.3 should fix this behaviour

I've also pulled the 1.10.2 package from that release

**Comment by bartreardon** [comment]
so the reason it was n, m, w and q specifically is those keys control "new window", "minimise window", "close window" and "close app", when used in combination with the `command` key. The code I was using didn't properly catch the command+key event and was just capturing "key"....hence those keys were blocked (and just pressing `q` would quit the app)

how embarrassing 😳
