### ISSUE TITLE
FR: Allow disabling `--infobutton`

### ISSUE THREAD

**Issue by dan-snelson** [bartreardon/swiftDialog#118]
Feature Request: Please allow disabling `--infobutton`.

<img width="932" alt="Screen Shot 2022-05-02 at 12 26 34 PM" src="https://user-images.githubusercontent.com/24623109/166708855-8983c52e-03a7-4676-a501-b7068d33228d.png">

**Comment by dan-snelson** [comment]
(If you have the cycles, what'd be **cool** is if there was a new `--infotext` option which _wasn't_ a button, in addition to `--infobutton`; both of which would be mutually exclusive.)

**Comment by bartreardon** [comment]
@dan-snelson I've added this in. It's a simple `--infotext` which when invoked, replaces the info button

**Comment by dan-snelson** [comment]
Excellent! Can’t wait to try it out.
