### ISSUE TITLE
Lists can not have items appended or removed

### ISSUE THREAD

**Issue by WardsParadox** [bartreardon/swiftDialog#120]
Some times, dialogs might need to have the list modified to add items or remove items from the list.

The only way to do this currently requires resetting the list to "fake" the method, but this resets the states of each list item.

**Comment by bartreardon** [comment]
implemented with the following commands:
Delete a row:
`echo "listitem: index: 0, delete:" >> /var/tmp/dialog.log`
or
`echo "listitem: title: Some Row Title, delete:" >> /var/tmp/dialog.log`

to add an item:
` echo "listitem: add, title: Some Title, statustext: Hi There, status: pending" >> /var/tmp/dialog.log`
