### ISSUE TITLE
FR: Support for radio buttons

### ISSUE THREAD

**Issue by mm2270** [bartreardon/swiftDialog#121]
Hi there. In addition to the checkbox option that swiftDialog already supports, I'd like to see an option for radio buttons.

Although probably less commonly used than checkboxes, radio buttons have their uses when you want to present a list of mutually exclusive options to a user, so only one of the items can be selected, not multiples.

Some other dialoging tools out there support this, and I'd like to see it be an option with swiftDialog too, it at all possible.

**Comment by mm2270** [comment]
BTW, I just wanted to mention that I'm aware that a selectable list is an alternative to radio buttons, since list selections are also mutually exclusive.
However, for some scenarios, using radio buttons seems more efficient and easier. For example, if you only need to present 2 - 3 choices, using a selection list seems like overkill. I'd prefer to leave those lists for larger numbers of choices.

**Comment by bartreardon** [comment]
yeah, that's a fair assessment. As far as implementation is concerned, the dropdown and radio buttons are the same code just with a different style attached to it. Will add this as a FR for 1.11

**Comment by bartreardon** [comment]
Closing this one off - radio buttons were added as a subset of select lists in v2.2 https://github.com/bartreardon/swiftDialog/wiki/Select-Lists-and-Radio-Buttons
