### ISSUE TITLE
Bug (?): `--titlefont` size spec overrides `--messagefont` size spec

### ISSUE THREAD

**Issue by mm2270** [bartreardon/swiftDialog#122]
I'm seeing some odd results that I think may be a bug, unless it's expected behavior, but I wasn't under the impression it was.

If I use dialog and specify `--title` and `--titlefont` and specify a size for the title, it seems to override my `--messagefont` size specification in the same dialog.

Examples, using the latest 1.10.3 release.

This example leaves out `--titlefont` but includes a size for `--messagefont`
```
dialog --title "My title" --message "This is the message text" --messagefont "name=Courier,colour=#ADD8E6,size=25" --ontop --icon none --small
```
I get a dialog that looks like this:

![image](https://user-images.githubusercontent.com/3653600/168683161-0e1682ce-ef2d-4a08-aebb-fdd6fdde8a1a.png)

If I add the titlefont spec, like so:
```
dialog --title "My title" --titlefont "size=14" --message "This is the message text" --messagefont "name=Courier,colour=#ADD8E6,size=25" --ontop --icon none --small
```
The dialog ends up looking like this:
![image](https://user-images.githubusercontent.com/3653600/168683252-4b636145-36e6-425a-bf73-6965a28b1dcb.png)

Essentially the title font size seems to override the message font size. I checked to see if specifying a font or font family also overrides the font name for the message text, but it doesn't. The message text retains the font, but not its size.

So, is this expected behavior? I would think those 2 items should be independent from each other, but so far I've been unable to decouple them.

**Comment by bartreardon** [comment]
ah, good find

spot the issue 😳https://github.com/bartreardon/swiftDialog/blob/34b714e4cf8b58588a20b3c8e243984ca13895fd/dialog/UI/MessageContentView.swift#L28

**Comment by mm2270** [comment]
Ah, yeah, now that you're pointing to it, I can see the issue, lol. 😀 
Well, glad it's an easy fix anyway.

**Comment by bartreardon** [comment]
fixed in this commit https://github.com/bartreardon/swiftDialog/commit/f32c13a00be9e059159dc8e030c7ed1714de580a
