### ISSUE TITLE
Buttons not returning any code as described

### ISSUE THREAD

**Issue by mubeers** [bartreardon/swiftDialog#130]
Dialog is very useful & helpful tool and i am planning to use dialog as replacement for DEPNotify.  Need help for below, 

1. I am not getting return codes and i`m in dialog version 1.10.4
2. dialog.log file commands not applying in full screen mode skipping many..

Button Name | Optional | Hotkey | Return Code
button1          | No           | Enter    |  0
button2         | Yes          | Esc       |  2
infobutton     | Yes          |              | 3

**Comment by bartreardon** [comment]
Hi, I'm not seeing what you're seeing. on 1.10.4 and I run `dialog -2 -3 --quitoninfo` the exit codes are `0` for ok `2` for cancel and `3` for info. (checked with `echo $?`)

fullscreen mode does not support the full set of dynamic update features at this point in time.

**Comment by mubeers** [comment]
Thanks for your quick reply, it will be helpful if we get the full screen mode supports all, now i am using combination of both Jamfhelper and Dialog to fulfill. 

About the return code, Yes when i run the echo $? , getting the codes. But when i  try to store it in a variable like, choice=$(dialog -2 -3 --quitoninfo) it is not storing. will use echo for now. Thank you so much

**Comment by bartreardon** [comment]
ah, ok. because exit codes are not sent to stdout , `choice=$(dialog -2 -3 --quitoninfo)` won't work.
The usual way to do this is to do the following:
```bash
dialog -2 -3 --quitoninfo
result=$?
```

Will close this one as it's standard bash behaviour
