### ISSUE TITLE
background art position (--bgposition) does not change when --bgfill 'fill' mode is used.

### ISSUE THREAD

**Issue by bradtchapman** [bartreardon/swiftDialog#132]
Expected behavior:
When using background art with the --bgfill fill option, I expect that the --bgposition switch will move the artwork around based on the chosen anchor point: center, left, topright, etc.  

What I'm actually seeing is that the artwork is anchored to the top / left corner of the window and scales out from there.

The only option that respects --bgposition is --bgfill fit.

**Comment by bradtchapman** [comment]
Here are some examples.  I've embedded the parameters into the screenshot as a list item.

Thanks!

<img width="932" alt="bg2-fit-center" src="https://user-images.githubusercontent.com/32527656/171052517-fb3ac92e-4ce4-40ae-99c8-6867a626dae6.png">
<img width="932" alt="bg2-fill-right" src="https://user-images.githubusercontent.com/32527656/171052524-bba70468-780b-421a-9df3-6da253ff7040.png">
<img width="932" alt="bg2-fill-center" src="https://user-images.githubusercontent.com/32527656/171052529-d02bbdf7-a050-4e79-8d9c-e257a8246285.png">
<img width="932" alt="bg2-fit-top" src="https://user-images.githubusercontent.com/32527656/171052532-1a291428-2a78-47af-b584-3613f28baa77.png">
<img width="932" alt="bg1-fit-right" src="https://user-images.githubusercontent.com/32527656/171052534-1104defe-4655-4fe5-b3a9-e221d5606950.png">
<img width="888" alt="bg1-fit-center" src="https://user-images.githubusercontent.com/32527656/171052537-7cc641b4-cee3-4b03-956a-65dadb631889.png">
<img width="888" alt="bg1-fill-center" src="https://user-images.githubusercontent.com/32527656/171052539-80350e6b-b643-4800-a1fa-f352e15f78db.png">

**Comment by bartreardon** [comment]
@bradtchapman I'm not seeing this behaviour with reasonably sized images.
something to be aware of is that the image used needs to be appropriate for the use. if the image you want to use is larger or a significant % of the size of the window then positioning it it won't work very well. e.g. use a logo of 100x100 and `--bgposition left|right|top|bottomright` etc should work as you expect. For larger images meant to fill the entire background, `fit` will re-size the image until it fits (result may be letterboxed), `fill` will fill the window (bg may be cropped, fixed on the top left corner).

**Comment by bartreardon** [comment]
Bunch of examples to show what I see (image is 200x200px)

![image](https://user-images.githubusercontent.com/3598965/171097607-3ff7f414-e123-41af-ae22-51546613d9ef.png)

![image](https://user-images.githubusercontent.com/3598965/171097669-0d4df8f2-6ea5-439c-a474-0db2912ee454.png)

![image](https://user-images.githubusercontent.com/3598965/171097724-47b7388f-993d-4b8b-bfdc-547b8a82159f.png)

![image](https://user-images.githubusercontent.com/3598965/171097843-d6a1363c-9d02-4b18-88b2-1966d797e578.png)

**Comment by bradtchapman** [comment]
I was using some logos as an example; however, there may be a case where someone wants to use a carefully prepared 'wallpaper' as the background with a logo or deesign element **placed carefully** in the center of that image.

If the background art is larger than the swiftDialog window, then using "fill" currently results in the background art being way off center.  And using 'fit' is not awesome either, because the proportions might not match the window, and there is a gap on the top/bottom or the sides.

Is there a way for each bgposition argument — topleft, topright, center, etc.— to also use that point in the image as the anchor position? 

Example for a 600x400 window, and a 1200x800 background image;

--bgposition topleft: anchor the image at 0,0 to window position 0,0 and scale fill down/right.
--bgposition bottomright: anchor the image at 1200,800 to window position 600,400 and scale fill up/left.
--bgposition bottom: anchor the image at 600,800 to window position 300,400 and scale fill up/outwards.
--bgposition center: anchor the image at 600,400 to window position 300,200 and scale outwards.

See attached images of how it would look wrong, as well as the original wallpaper used for the example.

<img width="600" alt="Screen Shot 2022-06-02 at 12 09 49 AM" src="https://user-images.githubusercontent.com/32527656/171573680-0959f8c3-147a-4aca-a455-69f2916601ac.png">

<img width="600" alt="Screen Shot 2022-06-02 at 12 10 03 AM" src="https://user-images.githubusercontent.com/32527656/171573671-caeda253-ad0b-46c8-a454-480024fc4933.png">

![electron-wallpaper](https://user-images.githubusercontent.com/32527656/171573771-f93c3b41-4d1b-4ed8-9a96-73657f41861b.jpeg)

**Comment by bartreardon** [comment]
ah ok. how's this?

`-bf fit -bp bottom`
![image](https://user-images.githubusercontent.com/3598965/171591273-68f5e7f1-9b07-4914-a28a-ac7941ddbb65.png)

`-bf fit -bp bottom`
![image](https://user-images.githubusercontent.com/3598965/171591357-7aa64260-4a2e-49b2-9f62-6e8b0fb7eabc.png)

`-bf fill`
![image](https://user-images.githubusercontent.com/3598965/171591504-fa341d3b-54ce-46f4-a260-bcbcf064a6c2.png)

`-bf fill -bp left`
![image](https://user-images.githubusercontent.com/3598965/171591614-4bc9dea4-a69a-4215-9a56-8bf4fbe5cf0f.png)

`-bf fill -bp right`
![image](https://user-images.githubusercontent.com/3598965/171591706-0598da37-5fc7-4cdc-99e7-453cb76b25e5.png)

**Comment by bartreardon** [comment]
if the image was taller than it was wider than for a `-bp fill` you could adjust the position top and bottom as desired

**Comment by bradtchapman** [comment]
Yep, this looks as expected.  Thanks!

**Comment by bartreardon** [comment]
fixed in [1.11](https://github.com/bartreardon/swiftDialog/releases/tag/v1.11.0)
