### ISSUE TITLE
Consider changing -bf and --bgfill to -bs and --bgscale.

### ISSUE THREAD

**Issue by bradtchapman** [bartreardon/swiftDialog#133]
The option --bgfill (-bg) could be made more agnostic and refer to its function, which is to 'scale' the artwork using the preferred technique.  

Usage:
`-bs, --bgscale [fill | fit]`

**Comment by bartreardon** [comment]
`-bs`, `--bgscale` are available in [1.11](https://github.com/bartreardon/swiftDialog/releases/tag/v1.11.0)
