### ISSUE TITLE
Allow adjustment of line spacing for the list view

### ISSUE THREAD

**Issue by bradtchapman** [bartreardon/swiftDialog#135]
Hello,

Please allow some adjustment of the frame height for a 'compact' list view, or set it relative to the messageFontSize.

Suggestion:

`--liststyle [expanded, regular, compact]`

*warning: pseudocode incoming!  the floor(int()) is intended to indicate rounding to the nearest whole number.*

`expanded =  .frame(height: floor(int(messageFontSize * 2.2)))`
`regular = .frame(height: floor(int(messageFontSize * 1.8)))`
`compact = .frame(height: floor(int(messageFontSize * 1.4)))`
 

https://github.com/bartreardon/swiftDialog/blob/c35519c5ef8590422092f88fafa7b5847c575642/dialog/UI/ListView.swift#L80

**Comment by scriptingosx** [comment]
I like this idea of "size" presets very much. I think the list font size might need to be adjusted for each size as well

**Comment by bartreardon** [comment]
ok, so having a play with this. Font and status icon are defined by the `messagefont` argument and the height is also derived by the font size. `compact` reduces the listitem height by 15, `expanded` increases it by 15.

`--liststyle compact --messagefont size=15`

![image](https://user-images.githubusercontent.com/3598965/174571879-6cf3a4c3-a797-4f3d-bc9e-f4c6d98802ae.png)

`--liststyle expanded --messagefont size=15`

![image](https://user-images.githubusercontent.com/3598965/174570338-b7544b5c-17f1-4f81-b96a-d6e8fda98d89.png)

`--liststyle compact --messagefont size=30`

![image](https://user-images.githubusercontent.com/3598965/174570561-ad089809-274d-43eb-ab04-257088fce02b.png)

`--liststyle expanded --messagefont size=30`

![image](https://user-images.githubusercontent.com/3598965/174570664-3d3907e2-fef4-423a-b16b-a310922473c8.png)

**Comment by dan-snelson** [comment]
`compact` is just a little _too_ compact for me, @bartreardon.

Could it be percentage-based, so the taller the window, the more spacing between list items?

<img width="932" alt="Screen Shot 2022-06-28 at 3 49 40 PM" src="https://user-images.githubusercontent.com/24623109/176307533-e92f47d0-425a-430e-9008-740a0c108910.png">

<img width="932" alt="Screen Shot 2022-06-28 at 3 55 16 PM" src="https://user-images.githubusercontent.com/24623109/176307571-ae840fbb-f461-4a67-994b-59a3d0950323.png">

**Comment by bartreardon** [comment]
@dan-snelson so you want a compact view that expands to fill the available space? I can look at a proportional sizing, so if you have 10 items it will spread the items out to fill the height of the view. Is that what you're after?

**Comment by scriptingosx** [comment]
I agree that the `compact` view seems a little too compact
![image](https://user-images.githubusercontent.com/1933192/176400649-9ceb7328-135e-4b15-90d5-efca55950921.png)

Not sure I like the idea of automatic adjustment, though. There would have to be a cut-off where it switches to a scroll view. and that might lead to too many dials and switches?

**Comment by dan-snelson** [comment]
@bartreardon No, `compact` doesn't need to **fill** the available space, but be proportional based on `--height` (**not** the number of list items).

However, as @scriptingosx stated, if there's too many dials and switches, please consider changing `compact` from a `15` point reduction to a `10` (?) point reduction.

**Comment by bartreardon** [comment]
trying to wrangle a percentage of height is a bit of a PITA. the height of a view isn't a 1:1 match with the "height" in points. Happy though at this stage to adjust compact spacing though.

Screenshot: regular spacing on the left, -10 in the middle and -15 on the right. LMKWYT

![image](https://user-images.githubusercontent.com/3598965/176427339-4a45dfb3-ac4e-45d2-9a1f-0ad75ab7c9c8.png)

**Comment by scriptingosx** [comment]
I think the middle one looks best.

Since changing the message font size also adjusts the line height, you can also change that for more information density.

Thank you, I like this!

**Comment by bradtchapman** [comment]
Thirded.  Middle one is juuuuust right, Goldilocks!

**Comment by bartreardon** [comment]
sounds like a consensus to me.
