### ISSUE TITLE
Bug (?): Using `--small` to control dialog size overrides `--iconsize`

### ISSUE THREAD

**Issue by mm2270** [bartreardon/swiftDialog#136]
I'm using the latest release, version 1.11, and I'm seeing behavior where the `--iconsize` flag is being overridden or ignored when using the `--small` flag to control the dialog window size.

Here's an example script showing the behavior and screenshots showing each window.

```
#!/bin/zsh

/usr/local/bin/dialog \
--title "Patch Management" --message "The following software updates are ready to be installed on your Mac.  \n\n - Adobe Reader DC \n\n You have 5 deferrals remaining. Click \"Update Now\" below to start these updates.  \n\n You will be given an opportunity to close any open applications and files in these programs before the installations start." \
--messagefont "size=14" \
--button1text "Update Now" \
--button2text "Defer" \
--icon  "/System/Library/PreferencePanes/SoftwareUpdate.prefPane/Contents/Resources/SoftwareUpdate.icns" \
--iconsize 48 \
--ontop

/usr/local/bin/dialog \
--title "Patch Management" --message "The following software updates are ready to be installed on your Mac.  \n\n - Adobe Reader DC \n\n You have 5 deferrals remaining. Click \"Update Now\" below to start these updates.  \n\n You will be given an opportunity to close any open applications and files in these programs before the installations start." \
--messagefont "size=14" \
--button1text "Update Now" \
--button2text "Defer" \
--icon  "/System/Library/PreferencePanes/SoftwareUpdate.prefPane/Contents/Resources/SoftwareUpdate.icns" \
--iconsize 48 \
--ontop \
--small
```
Here are screenshots of each window that appears from the above script. Note how in screenshot 1, where I am NOT calling the `--small` flag, the icon is scaled to 48 pixels. In screenshot 2 when I call that flag, the icon appears much larger. In fact, it always appears at the same size no matter what size I use for `--iconsize`, so I think it's being ignored.

Screenshot 1:
![image](https://user-images.githubusercontent.com/3653600/172700418-551f4a92-daba-4c2c-863c-f5b299ef1d34.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/3653600/172700533-151e2d77-b33e-46ab-9312-841b6c6f8b2c.png)

**Comment by mm2270** [comment]
@bartreardon I see it looks like you have a fix ready for this issue from your post above. Any idea when this may make it into a new office release? Will it be the next build? If so, do you have any thoughts on when that's coming?

Sorry to bug on it. It's just that I don't have the setup right now to build sign and notarize the app myself or I would do that. And I'd prefer to only deploy out a signed and notarized version of the app if I can help it.

Thanks!

**Comment by bartreardon** [comment]
yeah, will be in the next release which will be pretty soon (next day or so). Just finalising the last detail on one of the other fixes making its way in.

**Comment by mm2270** [comment]
Excellent! Thanks.

**Comment by mm2270** [comment]
@bartreardon  It looks good! So far in my tests with a script that was affected by the bug the icon sizes are being respected when using the small window size. I'll poke at it just a little more, but I don't expect to see any other issues.
Thanks!
