### ISSUE TITLE
FR: Support for file selection

### ISSUE THREAD

**Issue by phillymjs** [bartreardon/swiftDialog#137]
Please consider adding the ability to select files, that's the only thing preventing me from switching to swiftDialog completely and letting go of cocoaDialog.

https://web.archive.org/web/20200628050802/https://cocoadialog.com/v2/#fileselect_control

Using a picker would be sufficient, but if it were possible to also drag and drop a file into the dialog as well, that would be fantastic.

**Comment by bartreardon** [comment]
what's the use case for file selection and how does it get used?

I'd expect that the all dialog would do is return the path of the file to your calling script. there's wouldn't be any validation done (that would be left up to the script).

I'm not super familiar how this was used in cocoadialog so want to make sure I understand the functionality.

**Comment by dan-snelson** [comment]
I'd love to stop using [Pashua](https://github.com/BlueM/Pashua) for my on-prem Jamf Pro server deployment tool.

(I select a downloaded `ROOT.war` — and only `.war` files — which is then expanded and configured.)

**Comment by phillymjs** [comment]
My use case is a script in Jamf Self Service to allow users to install non-standard apps without admin rights. They need to be able to select the .app or .pkg they need installed.

Dragging and dropping a file into a text field works currently (i.e. the path is put into the field) if the text field is clicked on to select it first.

Honestly, I could get by with drag-and-drop into an existing text field if it wasn't required to click on it first, but having the actual file picker would be a bonus.

**Comment by mm2270** [comment]
Nice! This will be a great addition to the tool.

**Comment by phillymjs** [comment]
> `--textfield "Pick an image (PNG),fileselect,filetype=PNG"`
> 
> Example: ![image](https://user-images.githubusercontent.com/3598965/182844086-7fe78fdc-2a0a-4508-9b75-06d8854926c3.png)
> 
> ![image](https://user-images.githubusercontent.com/3598965/182844558-22c67857-3173-4541-a615-c16c8b2fb85a.png)

Quick question, what's the parameter name to specify the file selection button text? When we try your sample code the button reads "button-select"
<img width="631" alt="button-select" src="https://user-images.githubusercontent.com/5480797/188221087-ce43f6d0-abce-4492-8e92-60b8b6ef4eb5.png">

**Comment by precaf** [comment]
I previously used CocoaDialog and Pashua for file selection but both are no longer in development. I have had to move to the homebrew version of Zenity, which has many overlapping features with swiftdialog. But I absolutely need a simple, elegant file and directory picker. swiftdialog's is not there yet. I can pick a file but it unnecessarily clutters the dialog box with a text field and prompts and buttons whereas the other 3 just pick a file or directory. Also, swiftdialog's directory selection is an afterthought (as the file selector seems to be as well), and I have not found a way to select ONLY directories with it. I will move from Zenity to swiftdialog in a flash if the file/directory picker problems are sorted out. But for now, this is a show-stopper.

**Comment by bartreardon** [comment]
Do what you need to do @precaf but just so you know, I'm not paid to write or maintain this project (other than what I get from my employer which I would get anyway whether I wrote this app or not). Barking commands like "do this or I go elsewhere" will do nothing to encourage anyone to help you.

**Comment by precaf** [comment]
Nobody is barking at you. You’ve got something that could be very useful for more than the niche admin user community if only an important use case were addressed. I’m already using Zenity. I’d switch if swiftDialog were usable. Sorry I hurt your feelings but that’s a very different message than "do this or I go elsewhere.”

On Mar 27, 2024, at 5:03 PM, Bart Reardon ***@***.***> wrote:

﻿

Do what you need to do @precaf<https://github.com/precaf> but just so you know, I'm not paid to write or maintain this project (other than what I get from my employer which I would get anyway whether I wrote this app or not). Barking commands like "do this or I go elsewhere" will do nothing to encourage anyone to help you.

**Comment by bartreardon** [comment]
Don't worry, my feeling weren't hurt in the slightest. I'll let you know though that "I'll use your app if you would only do this one thing that several other apps do" is not the motivation you think it is - quite the opposite. I think it's a rude way to approach someone working for free on an app you didn't pay for. 

If you have an idea for an improvement then I suggest you raise it as a seperate feature request (since this one was closed a while ago) detailing the layout or behaviour that you think would be beneficial. Don't include comparisons to other apps, just describe the behaviour.
