### ISSUE TITLE
WebUIView

### ISSUE THREAD

**Issue by motionbug** [bartreardon/swiftDialog#138]
Hello @bartreardon 

Thank you for the wonderful app **swiftDialog**

I was looking at the project and was wondering if it is possible to create a webview with swift using Webkit. 

The idea is that we could use it to display data on a page and or use it to download an MDM profile.

Just an idea.. comments to grow

**Comment by bartreardon** [comment]
Good suggestion. This has been on my want/todo list for a while

**Comment by motionbug** [comment]
Thanks

**Comment by robatjamf** [comment]
Just to add, working with a customer that would like to show the code of conduct (that changes) and its on a public site, so we could show the webpage of the code of conduct with the I Agree... just and idea

**Comment by motionbug** [comment]
awesome! Thank you mate

**Comment by bartreardon** [comment]
Added in 2.0
