### ISSUE TITLE
Selectable lists - fails to import any JSON, even the example given in documentation

### ISSUE THREAD

**Issue by bradtchapman** [bartreardon/swiftDialog#141]
The following command, using only the example JSON from the Selectable Lists page, results in "JSON Import Failed."

```
/usr/local/bin/dialog -d --title "test window" --jsonstring '{
"selectitems" : [
		{"title" : "Select 1", "values" : ["one","two","three"]},
		{"title" : "Select 2", "values" : ["red","green","blue"], "default" : "red"},
		{"title" : "Select 3", "values" : ["up","down","left","right"]}
	]
}'
```
https://jsonlint.com says this is valid JSON.

**Comment by bradtchapman** [comment]
btw this is version 1.11.1, downloaded two days ago.

**Comment by bartreardon** [comment]
`--jsonstring` doesn't like newlines in the json structure because in order to be able to support newline characters (i.e the literal text `\n`) within a `--message` block it will convert `\n` to `\\n` and this breaks the valid json check. Stick everything on one line and it will work.

**Comment by bartreardon** [comment]
which BTW is why JSON rocks - you can smash an entire json into a single line and it's still valid. Try that with YAML and see how far you get 😛

**Comment by bradtchapman** [comment]
Step 1. Open BBEdit.
Step 2. Paste JSON.
Step 3. Click Text > Remove Line Breaks.
Step 4. Do a celebratory fist pump in the air.
Step 5. Bow in gratitude toward the author.
Step 6: Humbly ask the author to update [**this page**](https://github.com/bartreardon/swiftDialog/wiki/Using-JSON-to-specify-Dialog-options) with a bit more clarity and remind implementers to smash their JSON into a single line.  :)

**Comment by bartreardon** [comment]
it's a bit of a compromise I know - One thing I'd like to do is let you have multiple `--jsonstring` so you can create content piecemeal.

**Comment by bartreardon** [comment]
JSON page has been updated BTW with a note on how `--jsonstring` will expect input

**Comment by Honestpuck** [comment]
> which BTW is why JSON rocks - you can smash an entire json into a single line and it's still valid. Try that with YAML and see how far you get 😛

Of course it totally borks if you put a comma after the last item in an array, unlike well designed languages such as Python.
