### ISSUE TITLE
Returning the value of a selectitems array does not work in Ventura Public Beta

### ISSUE THREAD

**Issue by kdrwygvh** [bartreardon/swiftDialog#145]
Given a jsonfile that contains;

`"selectitems"" [
{
  "title":"Country",
  "values": [
    "Albania".
    "Algeria",
    ...`

and specifying that dialog should output the result as json, nothing is returned in SelectedOption

**Comment by bartreardon** [comment]
I'm not seeing this behaviour in Monterey or Ventura. Can you provide a full json example?

One thing of note, when outputting json, of you have multiple dropdown lists, you will not get "SelectedOption".

**Comment by bartreardon** [comment]
I think think might be a result of extra debugging being present in the Ventura beta's.

Will look at this for v2 which should be out before macOS 13 is released.

**Comment by bradtchapman** [comment]
Same — I think I reported this to @bartreardon last week because I have a dialog with 3 `selectitems` drop downs.

**Comment by kdrwygvh** [comment]
FWIW this issue seems to be resolved in the 2.0 preview builds. Assuming that the 1.x code is fixed now I'll close this .
