### ISSUE TITLE
FR: icons in list view

### ISSUE THREAD

**Issue by scriptingosx** [bartreardon/swiftDialog#148]
it would be nice if you could add an app icon _before_ the title in the list view...

**Comment by bartreardon** [comment]
Agree - in fact ;) https://github.com/bartreardon/swiftDialog/blob/deb4605f9bd7cfc1e0af88319d1ebd4e997a7780/dialog/extras/TrackProgress.swift#L384-L385

**Comment by bartreardon** [comment]
How's this look as an example? Icon height will match the height of the row. Using the same view as the main icon so SF symbols (with colour mods) also work. 

<img width="599" alt="image" src="https://user-images.githubusercontent.com/3598965/182604151-3eabe9b5-3f77-4949-9b88-c522676e3314.png">

**Comment by scriptingosx** [comment]
beautiful!

**Comment by mm2270** [comment]
Ok, wow, liking this! That looks great. Can't wait until that's added to the product.

**Comment by dan-snelson** [comment]
With version `1.11.2.2976`, if `--overlayicon` is included, the `listitem` also displays the overlay icon. (My personal preference is that `--overlayicon` only be applied to the main icon.)
<img width="932" alt="Screen Shot 2022-08-06 at 6 11 16 AM" src="https://user-images.githubusercontent.com/24623109/183248693-dbf0aadf-be68-4be5-95e7-53ad9edc441d.png">

Example with `--overlayicon` commented-out:
<img width="932" alt="Screen Shot 2022-08-06 at 6 12 22 AM" src="https://user-images.githubusercontent.com/24623109/183248739-46ebd998-2240-4e13-bff3-4375fb5fc2ec.png">

**Comment by dan-snelson** [comment]
With version `1.11.2.2988`, `--overlayicon` is working as expected.
<img width="932" alt="Screen Shot 2022-08-08 at 12 02 04 AM" src="https://user-images.githubusercontent.com/24623109/183356669-95e0ab51-3496-438e-ab6d-fe65cfb70473.png">

**Comment by mm2270** [comment]
Nice! So, maybe I'm missing it, but what is the exact syntax you need to use to add these icons into the list view? I see in the pre-release notes it mentions this was added, but it doesn't explain how its used. Thanks!

**Comment by dan-snelson** [comment]
@mm2270: Add `icon:` to your `listitem`:

https://github.com/dan-snelson/dialog-scripts/blob/development/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L574

**Comment by mm2270** [comment]
@dan-snelson Thanks Dan! Got it working. I was on the right path actually.
Nice work on your onboarding workflow btw!

**Comment by bartreardon** [comment]
@mm2270 https://github.com/bartreardon/swiftDialog/wiki/Item-Lists#advanced as well.
