### ISSUE TITLE
Default value for --commandFile help text is incorrect

### ISSUE THREAD

**Issue by tcoliver** [bartreardon/swiftDialog#151]
The value of the help text for the --commandFile option is shown as /var/log/dialog.log. It should be /var/tmp/dialog.log. This shows up when running dialog --help from the command line and also in the [Command Line Options](https://github.com/bartreardon/swiftDialog/wiki/Command-Line-Options) wiki page.

**Comment by tcoliver** [comment]
I went ahead and created a pull request ([PR #152](https://github.com/bartreardon/swiftDialog/pull/152)) for the change to the cli help text. I don't know of a way to do one for the wiki.

**Comment by bartreardon** [comment]
Nice find. Thanks :)
