### ISSUE TITLE
Required Text Field Message Repeated

### ISSUE THREAD

**Issue by dan-snelson** [bartreardon/swiftDialog#156]
With swiftDialog `1.11.2.2988`, the required field message is displayed multiple times.

<img width="932" alt="Screen Shot 2022-08-10 at 7 24 20 PM" src="https://user-images.githubusercontent.com/24623109/184049752-9a9b38ee-810d-4939-a2be-e313d52fd945.png">

<img width="932" alt="Screen Shot 2022-08-10 at 7 24 13 PM" src="https://user-images.githubusercontent.com/24623109/184049776-c13479a3-5402-4b8f-a680-5cd2331acfe1.png">

## Testing Script

```
#!/bin/zsh

rm /var/tmp/dialog.log
touch /var/tmp/dialog.log
demoName="Required Text Field Message Repeated"
/usr/local/bin/dialog --title "$demoName" \
--quitkey k \
--messagefont "size=14" \
--ontop \
--moveable \
--textfield "Asset Tag",required=true,prompt="Please enter your Mac's seven-digit Asset Tag",regex="^(AP|IP)?[0-9]{6,}$",regexerror="Please enter (at least) seven digits for the Asset Tag, optionally preceed by either AP or IP." \
--message "An **Asset Tag** is required and needs to be provided in the following format:  \n• Seven digits (or more)  \n• Optionally proceeeded by _AP_ or _IP_  \n\n**Steps to replicate**  \n\n1. Click **OK** three times  \n2. Enter _five_ random numbers  \n3. Click **OK**  \n4. Observe the required field message is repeated multiple times"
```

**Comment by bartreardon** [comment]
Can I just say @dan-snelson that I love the inclusion of the test script 🙂 - brilliant way to demonstrate and explain the issue

**Comment by dan-snelson** [comment]
LGTM with `1.11.2.3086`

<img width="932" alt="Screen Shot 2022-08-11 at 6 29 53 AM" src="https://user-images.githubusercontent.com/24623109/184133682-e846c8ef-e890-4105-8d9e-acefcf5b0328.png">
