### ISSUE TITLE
Bug: dialog stops accepting live updates if a "required field" error is triggered

### ISSUE THREAD

**Issue by bradtchapman** [bartreardon/swiftDialog#157]
As the title says, I have a dialog with required fields that is also taking live updates to the progress bar.  If I click "OK" with a required field incomplete or not matching regex, all live updates stop despite the script updating the command file.

**Comment by bartreardon** [comment]
https://user-images.githubusercontent.com/3598965/184090086-a23910bf-79dc-4bf6-9747-3d614f9fb246.mov

**Comment by bradtchapman** [comment]
Hey - I notice you marked the issue as fixed in your release notes.  Your demo video shows what happens if the field is left empty.  Try entering some text that doesn't match the regex rule and press OK.  It's when the error message pops up that dialog stopped listening.

**Comment by bradtchapman** [comment]
Maybe there's an issue specific to my build with the text editor.  I made it a required field also.  I'll double check that.

**Comment by bradtchapman** [comment]
Ohhhhh... is the video a demo of the feature working properly now?

**Comment by bartreardon** [comment]
delay in replying 🙂 - but yes. Was a relatively simple fix (although I introduced a bug where sending the `quit:` command to the command file orphaned the process that reads the log :/ .... but that's fixed now too 🙂
