### ISSUE TITLE
Bug: New mini window mode (version 1.11.2-3086) does not seem to respect --iconsize

### ISSUE THREAD

**Issue by mm2270** [bartreardon/swiftDialog#158]
In testing the latest preview build and invoking the new "mini" window size with the following code:
```
/usr/local/bin/dialog --title none --message "Something is being updated. Please wait" --mini --icon /System/Library/CoreServices/Installer.app --iconsize 16 --position topright --ontop --progress 0
```
I get this. The icon is not scaled to 16 pixels as I specified. I tried other integers as well (32, 64, etc), but the icon always appears at the same default size, it looks like.

![image](https://user-images.githubusercontent.com/3653600/184189236-874fb65b-c370-4da7-af8f-634812a5479e.png)

For contrast, this is the same code with `--mini` replaced with `--small`. Icon is scaled to 16 pixels.

![image](https://user-images.githubusercontent.com/3653600/184189528-87f6a811-d330-4493-abf0-1513baa5bdb5.png)

**Comment by bartreardon** [comment]
Correct. Thus is by design. Mini mode is mini in more than just size, it also only supports a subset of commands, one of those is iconsize.

**Comment by mm2270** [comment]
Ah, I see. Got it then, thanks!

Hmm. I wonder if it would be possible to have a default icon size for mini a bit smaller? It's a bit... large for such a small window mode. I can submit a FR is this is possible to do.
