### ISSUE TITLE
Feature Request: Timer to set banner to show every X hours

### ISSUE THREAD

**Issue by mat-griffin** [bartreardon/swiftDialog#160]
Would be nice if there was a timer.
For example set the banner to display every 60 minutes or every 3 hours.

Jamf is not great at this, you can have a policy to run once per day or on check-in but not twice a day or every 3 hours. 
If SwiftDialog had a timer the Jamf policy could be ongoing and on check-in but only display based upon the timer, usually achieved by writing a file on the Mac and then comparing before displaying.

Good example on Jamf Nation which I guess you could wrap around your SwiftDialog script but not an overly elegant solution.
https://community.jamf.com/t5/jamf-pro/run-a-policy-twice-a-day/m-p/234520

**Comment by bartreardon** [comment]
Yah, that's not a swiftDialog function, that's something you would build into a script called from a launchd or something with a`StartInterval` value of 3600 (1 hour) or some multiple thereof. 

swiftDialog just displays stuff - the logic around what to show and when is left up to the admin.

e.g.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>awesome.dialog.script</string>
	<key>Program</key>
	<string>/path/to/some/script.sh</string>
	<key>RunAtLoad</key>
	<true/>
	<key>StartInterval</key>
	<integer>10800</integer>
</dict>
</plist>
```
