### ISSUE TITLE
FR- Timer in mini mode

### ISSUE THREAD

**Issue by Doronkerub** [bartreardon/swiftDialog#161]
Currently, the `--timer` argument doesn't show anything while using `--mini`.
Using timers seemes to be a very reasonable use case for the mini mode.

**Comment by bartreardon** [comment]
Yup, as documented, `--mini` is a very much cut down view of swiftDialog. Internally it's a completely different window definition and has nothing to do with the main window other than re-using some of the same elements.

At this point I don't have plans to implement `--timer` in the mini view, but one could be constructed using the progress bar and a loop to update, or you can re-size the default dialog window, e.g. `dialog --timer --width 300 --height 120 --icon none --title none --message "### Processing  \nPlease Wait" --alignment centre`
