### ISSUE TITLE
Feature Request - Text Alignment Vertically in Window

### ISSUE THREAD

**Issue by kspitzer14** [bartreardon/swiftDialog#162]
Vertical Alignment flag.
Allow user to specify setting the message to be at the top, center, or bottom of a window.
![Screen Shot 2022-08-31 at 9 35 14 AM](https://user-images.githubusercontent.com/81643525/187787403-34fb70c1-1708-4154-941d-b571ffff2ab9.png)

**Comment by bartreardon** [comment]
Having a bit of a play with this.

Can certainly make an option that will allow vertical centring of text easily enough. Having top, centre, bottom isn't as straightforward

Something like this though ?
![image](https://user-images.githubusercontent.com/3598965/192129069-92bade13-b3eb-4d2a-bbfb-3cfb942c19a1.png)

**Comment by kspitzer14** [comment]
> Having a bit of a play with this.
> 
> Can certainly make an option that will allow vertical centring of text easily enough. Having top, centre, bottom isn't as straightforward
> 
> Something like this though ? ![image](https://user-images.githubusercontent.com/3598965/192129069-92bade13-b3eb-4d2a-bbfb-3cfb942c19a1.png)

That is exactly what I was looking for!

**Comment by bartreardon** [comment]
Fixed in 2.0

**Comment by kspitzer14** [comment]
It can't be said enough. Bart you are awesome!
