### ISSUE TITLE
Autoplay progress bar margins (and location?)

### ISSUE THREAD

**Issue by sidbena** [bartreardon/swiftDialog#164]
I would like the autoplay progress bar be given some margin to the dialog's edges. Could it perhaps even be put between the caption and its image, something like this (red lines):
<img width="932" alt="progress-suggestion" src="https://user-images.githubusercontent.com/16342210/188860429-887dba56-c5e2-4895-a02d-b19cde070dba.png">

Also, a small comment, the arrows on the sides of the image carousel aren't centered on the image object, see the blue line. It sticks out further on the left side. Or vice-versa, the image object isn't centered between the arrows. Not sure which is more true :P

**Comment by bartreardon** [comment]
Fixed in 2.0
