### ISSUE TITLE
Feature Request: Support for base64 encoded strings in place of images or icons

### ISSUE THREAD

**Issue by mm2270** [bartreardon/swiftDialog#165]
[Feature Request]
Can swiftDialog be made to accept base64 encoded strings for things like icons or other images (banners, etc.) instead of needing a path to a file or URL?

Other dialoging tools have this ability, so it seems like it's possible to do, and would be helpful in cases where we need a number of custom icons that aren't part of the SF Symbols set or already present on the machine, for example. Otherwise we always need to make sure the icons are available in some path as a physical file on disk, or in a URL path for them to be used in the dialog.

Thanks for considering.

**Comment by bartreardon** [comment]
@mm2270 can you check this feature out in the v2.0 preview? you should be able to specify `base64=<...>` anywhere an image is available. e.g. `--icon base64=<base64_string>`

**Comment by mm2270** [comment]
@bartreardon I have tried this under version 2.0 preview and it works beautifully! As far as I'm concerned this request is fulfilled in the new (upcoming) release. Thanks!

**Comment by bartreardon** [comment]
Fixed in 2.0
