### ISSUE TITLE
Feature request : possibility to disable button1 as default button

### ISSUE THREAD

**Issue by MiqViq** [bartreardon/swiftDialog#166]
Hi, I would find it useful if button1 could be disabled as a default button so it will not be selected while user is pressing enter/return.
And maybe any of the 3 buttons could be set as a default button for responding to enter/return.
This could be set using a parameter like defaultbtn (1,2,3 and 0 for none), if not defined then button1 could be the default.

**Comment by BigMacAdmin** [comment]
This would be a great enhancement.

**Comment by RIMorton** [comment]
This would meet the exact needs I currently have. Users are typing away and miss the dialog popup and hit return to send their message. Suddenly we start installing software that we warned them about in the dialog that they missed.

**Comment by bartreardon** [comment]
@RIMorton I think your specific needs can be met with the existing `--button1disabled` property which will do what is says, and can be re-enabled with sending `button1: enable` to the command file. Alternately you can use `--mini` mode with a `--progress` bar (which with no input will just bounce back and forth) to show something is happening.

This specific request is I think the case where you want button 1 available but not react to the default action (i.e. enter key). While that would also solve your needs it's a slightly different issue to the one you say you are wanting to solve.

**Comment by bartreardon** [comment]
available in [2.3](https://github.com/bartreardon/swiftDialog/releases/tag/v2.3.0)

`--button1text none`
