### ISSUE TITLE
Feature Request: Ability to apply 'alpha' transparency to icons

### ISSUE THREAD

**Issue by mm2270** [bartreardon/swiftDialog#167]
[Feature Request]

When using custom icons, it would be awesome to be able to apply an alpha value for transparency for the icon and have it be something we can change in a running dialog. I see that background images used in a dialog can have an alpha value applied, but not sure if this is really limited only to those types of image resources, or if it can apply to icons too.

What I'm thinking of is a way show the icon for an application (using a path to a png file) that is about to be installed and show the icon in a ghosted or semi translucent way, and then when installation is complete, change the icon to full opacity.

The only workarounds I can think of are to use either

- 2 icons for every application I would want to use this for - one at full opacity, and another one at, say 50% translucency, but that's a lot of work to create all those in advance. Possible, but kind of a lift to accomplish it.

- Or, less desirable, would be to use a generic icon like...

![image](https://user-images.githubusercontent.com/3653600/190507046-3f48ab13-1157-45c8-926c-d0ca77c0c464.png)

...which is from the SF Symbols set, and then switch to the actual app icon. Again, it's a possibility, but it would be nicer if we could use icons with a level of transparency instead.

**Comment by bartreardon** [comment]
This was resolved a while ago so not sure why I didn't close this off.

us `--iconalpha <value>` where <value> is a number between `0.0` and `1.0` where 0 is transparant and 1 is opaque (e.g. `0.5` would represent 50% transparency)
