### ISSUE TITLE
swiftDialog Preview 2.0 - List view is smaller than under 1.x

### ISSUE THREAD

**Issue by mm2270** [bartreardon/swiftDialog#169]
Hi! First off, I'm excited about the upcoming features and enhancements coming in swiftDialog 2. Thanks for continuing to improve this already awesome tool!!

I started playing with 2.0 a bit today, understanding that it's early days and there are going to be oddities with it that maybe don't exist in the last non preview release.

Once issue I'm seeing is that the List area has shrunk quite a bit in height from the previous builds. I have a custom patch workflow I've started using dialog with and under the 1.11.x release, I can have up to 5 items showing in a list in a dialog specced to a specific size in the script, along with some descriptive text in the `--message` area.
Under Preview 2.0, that same list only shows 3 items and there is a bunch of empty space above the list under where the `--message` text appears. The dialogs under both versions are exactly the same dimensions on screen, but in the new build, there's quite a bit of wasted space, at least in my opinion.

I'm including a couple of screenshots to show the difference between them to further illustrate it.

Here is what the dialog looks like with version `1.11.2.3095`

<img width="662" alt="dialog_1 11 2" src="https://user-images.githubusercontent.com/3653600/192896384-5c7515db-d5d5-494c-bc8f-b75a935a2719.png">

Here is what the same script produces with `2.0 Preview.3531`

<img width="662" alt="dialog_2 0 Preview" src="https://user-images.githubusercontent.com/3653600/192896406-6fd2691c-1b7c-4ecd-bafd-04c2d1e650fa.png">

In addition to the shorter space for the list, it's also not aligned with the buttons as it under the older version, which looks weird to me. There's a lot more "padding" to the left and right of the text area and the list area. The padding isn't necessarily a bad thing, and may be intentional, but I think the buttons should probably align better. It's a bit too noticeable when using a List in the dialog.

That being said, I kind of preferred the old way, but even if the new padding is how it will be now, I can live with that. But I don't think there should be all that empty space after the message and before the list. Hoping this can be fixed going forward.

Finally, I **_do_** like that the label text that shows up to the right on each list item is now the same font and size as the list items. I don't know if this was intentional or not, but I think it looks better than the smaller lighter text in the previous versions.

Thanks!

**Comment by bartreardon** [comment]
Yeah, that's a consequence of how scrollviews (the view containing the message content) seems to work when compiled with xcode 14. I've already fixed that up, and am considering removing scrollview altogether.

**Comment by bartreardon** [comment]
Fixed in the current preview release https://github.com/bartreardon/swiftDialog/releases/tag/v2.0Preview1

**Comment by mm2270** [comment]
Hi! I tried this out with the updated Preview, and yes, the List view is better, thanks! However, there still seems to be a bit of empty space in the text area. This time it's in the area where the title would normally be. I wonder if it's not respecting that my script has `--title "none"` in it because I'm using a banner image?

Here's a screenshot. As you can see, everything seems a bit pushed down.

<img width="662" alt="Screen Shot 2022-09-30 at 8 22 07 AM" src="https://user-images.githubusercontent.com/3653600/193270439-e369e90c-7691-4bf9-9e31-afff0c31a0f5.png">
