### ISSUE TITLE
2.0 Preview.3579: `textfield` alignment

### ISSUE THREAD

**Issue by dan-snelson** [bartreardon/swiftDialog#171]
With `2.0 Preview.3579`, the `textfield` alignment (i.e., **Asset Tag**) isn't as expected.

<img width="932" alt="Screen Shot 2022-10-02 at 6 09 00 AM" src="https://user-images.githubusercontent.com/24623109/193456649-c3d6c3bd-665c-4f7b-a96e-2c56aad71878.png">

<img width="932" alt="Screen Shot 2022-10-02 at 6 09 46 AM" src="https://user-images.githubusercontent.com/24623109/193456658-d46f8b88-b062-4f25-8df6-1b3e97c2b201.png">

**Comment by bartreardon** [comment]
how does this look? (ignore the dialog version in the corner)
![image](https://user-images.githubusercontent.com/3598965/194025441-8bbc5d7a-bffa-4e50-912f-8025137c0957.png)

**Comment by dan-snelson** [comment]
Seems too tight on the bottom to me. 

Can the “* Required Fields” be left-aligned?

**Comment by bartreardon** [comment]
@dan-snelson how's this?
![image](https://user-images.githubusercontent.com/3598965/194056334-fa838ea3-61da-49e1-a254-2cb1a9fabdc0.png)

**Comment by dan-snelson** [comment]
Bonzer!
