### ISSUE TITLE
2.0 Preview.3579: Remove UI "gaps"

### ISSUE THREAD

**Issue by dan-snelson** [bartreardon/swiftDialog#172]
Please consider removing several UI "gaps" in `2.0 Preview.3579`.

<img width="932" alt="Screen Shot 2022-10-03 at 3 55 59 AM" src="https://user-images.githubusercontent.com/24623109/193569932-480386c0-6a34-4b46-a028-b447bd4621ee.png">

**Comment by bartreardon** [comment]
Hi @dan-snelson, can you give this build a try and let me know what you think.

[Dialog 2.0.3624 Preview.zip](https://github.com/bartreardon/swiftDialog/files/9706422/Dialog.2.0.3624.Preview.zip)

**Comment by dan-snelson** [comment]
Significant improvement, @bartreardon.

As @mm2270 mentioned immediately above, please consider aligning the left and right buttons.

Thanks.

<img width="932" alt="Screen Shot 2022-10-04 at 6 30 36 PM" src="https://user-images.githubusercontent.com/24623109/193960551-fa56f193-31cc-433d-9b76-dcfe1829d9f6.png">

**Comment by dan-snelson** [comment]
Both options look good; I prefer the “same padding on the sides and bottom.”

**Comment by mm2270** [comment]
I have the same opinion as @dan-snelson. Either one looks better to me, meaning button alignment with the text or list is better than not. But the one with the consistent padding on the bottom and sides is probably the best approach. A little extra room on the bottom of the dialog is fine to me.

**Comment by dan-snelson** [comment]
This is lookin' sweet, @bartreardon:

<img width="932" alt="Screen Shot 2022-10-05 at 3 06 54 PM" src="https://user-images.githubusercontent.com/24623109/194382494-84fcbe2c-6cd6-49e8-ad03-97711a53e6c4.png">

Unless @mm2270 has any objections, I vote this issue can be closed.

**Comment by mm2270** [comment]
@dan-snelson No further comments from me. The margins, spacing and alignment all look really nice. It's your opened issue anyway, so if you're happy with it that should be good enough! 😃

**Comment by dan-snelson** [comment]
Thanks, @mm2270 …

… and thanks @bartreardon!
