### ISSUE TITLE
mini option does support titlefont color

### ISSUE THREAD

**Issue by Tribruin** [bartreardon/swiftDialog#179]
I am trying to create a dialog using the --option and colorize the title using --titlefont option. However, it does not appear that the title can be change in mini mode. 

`/usr/local/bin/dialog --ontop --title "Success" --titlefont "colour=#008000"`
<img width="888" alt="Screen Shot 2022-10-28 at 2 31 58 PM" src="https://user-images.githubusercontent.com/39201800/198718064-9435ea95-0e3a-44d5-88f1-0781f881b009.png">

`/usr/local/bin/dialog --ontop --title "Success" --titlefont "colour=#008000" --mini`
<img width="608" alt="Screen Shot 2022-10-28 at 2 32 33 PM" src="https://user-images.githubusercontent.com/39201800/198718176-e397ce9a-3e40-4bff-a9ea-e6a74a38c1a6.png">

Did I miss something in the Wiki about support for `--titlefont` with the `--mini` option

**Comment by bartreardon** [comment]
`--mini` doesn't support any formatting by deign, like markdown, images (other than the icon) and colours. At this point in time there's no plans to add any of that to mini mode.
