### ISSUE TITLE
Fix exit code for CMD+Q and --quitkey

### ISSUE THREAD

**Issue by BigMacAdmin** [bartreardon/swiftDialog#180]
If --quitkey value is set, and the user utilizes it, Dialog exits with exit code 10

If --quitkey is not used, and the user uses CMD+Q, then Dialog exits with exit code 0

`dialog -t test -m mess --quitkey ]; echo $?` #Exit code when using CMD+] is 10
`dialog -t test -m mess; echo $?` #Exit code when using CMD+Q is 0

**Comment by bartreardon** [comment]
Fixed in 2.0
