### ISSUE TITLE
Feature Request: Allow the `--notification` disclosure triangle to be optional

### ISSUE THREAD

**Issue by dan-snelson** [bartreardon/swiftDialog#182]
We're testing out the `--notification` feature in `2.0 Preview.3789`

`/Library/Application\ Support/Dialog/Dialog.app/Contents/MacOS/Dialog --notification --title "Title goes here" --subtitle "Subtitle goes here" --message "Message goes here.\nSecond line." --icon /System/Library/CoreServices/Finder.app`

<img width="370" alt="Screen Shot 2022-10-29 at 7 04 12 AM" src="https://user-images.githubusercontent.com/24623109/198833175-90cee3dc-8415-4ce4-90bf-7169b42715e4.png">

When the cursor hovers over the Notification, a disclousre triangle is displayed:
<img width="375" alt="Screen Shot 2022-10-29 at 7 04 19 AM" src="https://user-images.githubusercontent.com/24623109/198833273-69978f86-ef29-4c0d-9bd3-735dca0ce984.png">

Clicking the disclousre triangle reveals a larger version of the icon:
<img width="375" alt="Screen Shot 2022-10-29 at 7 04 28 AM" src="https://user-images.githubusercontent.com/24623109/198833328-01f829b4-3d38-46f2-9d53-61db9edcd1b4.png">

Please allow the `--notification` disclosure triangle to be optional.

**Comment by bartreardon** [comment]
can't be done - that's how notifications work with the swiftUI framework.
