### ISSUE TITLE
Feature Request: Allow the `--notification` snooze options to be optional

### ISSUE THREAD

**Issue by dan-snelson** [bartreardon/swiftDialog#183]
We're testing out the `--notification` feature in `2.0 Preview.3789` and have explicitly allowed Notifications for the `au.bartreardon.dialog` domain via MDM.

When testing with the following command …
`/Library/Application\ Support/Dialog/Dialog.app/Contents/MacOS/Dialog --notification --title "Title goes here" --subtitle "Subtitle goes here" --message "Message goes here.\nSecond line." --icon /System/Library/CoreServices/Finder.app`

… if users hover the cursor over the Notification …
<img width="375" alt="Screen Shot 2022-10-29 at 7 04 19 AM" src="https://user-images.githubusercontent.com/24623109/198834025-d8bb5ac1-0e4c-461c-b0c7-028855ec1b7b.png">

… then click the disclosure triangle, they observe an ellipse …
<img width="375" alt="Screen Shot 2022-10-29 at 7 04 28 AM" src="https://user-images.githubusercontent.com/24623109/198833759-6e91f60e-42b1-4a1e-92b5-5ae7ca0891a5.png">

… which reveals the "snooze" options:
<img width="233" alt="Screen Shot 2022-10-29 at 6 45 21 AM" src="https://user-images.githubusercontent.com/24623109/198833860-f6f4579f-a6dd-445e-8921-6d0c2c0d8bf8.png">

Since MDM has set these options, showing them to the user may generate frustrated support calls.

Please allow the `--notification` snooze options to be optional.

**Comment by bartreardon** [comment]
that's an OS/Notification Centre level setting that does not appear to be something that an app has any control over. This is the same as if someone went on do not disturb or into a specific focus mode. Any app that uses notifications will have the same conditions apply (for a notification without any additional content, the snooze options are available via right click)
