### ISSUE TITLE
Feature Request: Package dialog twice so we can choose different notification options

### ISSUE THREAD

**Issue by BigMacAdmin** [bartreardon/swiftDialog#184]
This is a wild request, I know:
I have a project I'm deploying, and I want to force "Alert" style notifications via MDM for my dialog notifications.

This conflicts with another project I have using Installomator where I would like users to be able to choose notification styles, or maybe force "Banner" style notifications.

I cannot do both, because Dialog is a single app bundle, so I can only choose one type of notification for various Dialog projects.

Is there some way around this? 

My half-baked idea is to have a second version of Dialog identical to the first which has a different app bundle ID so that we can have it show up in the Notification Center settings twice.

**Comment by bartreardon** [comment]
The usual way to deal with this is to have two app bundles that only do notifications within the main app bundle. This is how DataJAR Notify works. I can take a look and see what I can do. Would keep everything as-is and just add an `--alert` argument as well as the current `--notification` argument. Would be up to the admin to make sure a config profile is set to force the right behaviour for each type.

**Comment by BigMacAdmin** [comment]
Does that then mean you could potentially have multiple app bundles which use various icons in the notification?

Could you have a “warning” app bundle and a “info” app bundle and use different icons for each, or would they always use the icon of the parent app?

**Comment by bartreardon** [comment]
they are apps within the app so they can have different icons etc. will see what's required to move what I have now to nested app bundles

**Comment by bartreardon** [comment]
Had a bit of a fiddle - might not be able to make it for 2.0, at least not efficiently, but we'll see how we go

**Comment by BigMacAdmin** [comment]
Thanks for looking, Bart! The new Notification feature is fantastic already.

**Comment by bartreardon** [comment]
I played around with this for a bit and there are a number of tradeoffs and gotcha's, primarily if the sub-apps are bundled with swiftDialog then it breaks notarisation and if they are seperate then calling them from swiftDialog is a PITA.

 In a nutshell though, at this stage I won't be implementing functionality withing swiftDialog to provide dual notifications and alerts. If that's something you need then there are other apps that can do that (datajar notifier). I might revisit this as creating a minimal notification app is more than doable.
