### ISSUE TITLE
2.0.3792 Feature Request: Additional leading below `--title`

### ISSUE THREAD

**Issue by dan-snelson** [bartreardon/swiftDialog#186]
While it may be difficult to see in the screenshots below because of the dashed, red rule which has been added to highlight the issue, with version `2.0.3792`, the space below the `--title`'s horizontal rule is just a _little_ too tight for my personal preference.

<img width="932" alt="Screenshot 2022-11-08 at 2 55 42 PM" src="https://user-images.githubusercontent.com/24623109/200687651-f72112c8-9017-4eec-ae02-26f45c5bb50a.png">

<img width="932" alt="Screenshot 2022-11-08 at 2 57 39 PM" src="https://user-images.githubusercontent.com/24623109/200687735-3336fcb1-3fd9-4348-a65f-da8b2c4736bd.png">

<img width="737" alt="Screenshot 2022-11-08 at 3 00 23 PM" src="https://user-images.githubusercontent.com/24623109/200687757-f260435a-63dc-4610-a2b2-d3781c511ff9.png">

**Comment by BigMacAdmin** [comment]
I'll add on that the icon and message need some buffer space when using `--title none` as well
![Screenshot 2022-11-08 at 11 06 32 PM](https://user-images.githubusercontent.com/106293503/200762320-d0e7b067-9de3-4dbd-96c7-011e31a02b58.png)

**Comment by bartreardon** [comment]
![image](https://user-images.githubusercontent.com/3598965/201283893-dd767d84-9f9d-48b7-b81a-92591fe344da.png)

![image](https://user-images.githubusercontent.com/3598965/201284037-63df7bba-b26f-42d9-82c7-05cd93736fbb.png)

**Comment by dan-snelson** [comment]
Thanks for all your efforts, @bartreardon.

May we please see a sample with some descenders in the title?

```
dialog --title "Like your lorem ipsum extra crispy?" --message "Bacon ipsum dolor amet short ribs brisket venison rump drumstick pig sausage prosciutto chicken spare ribs salami picanha doner. Kevin capicola sausage, buffalo bresaola venison turkey shoulder picanha ham pork tri-tip meatball meatloaf ribeye. Doner spare ribs andouille bacon sausage. Ground round jerky brisket pastrami shank." --infotext
```

<img width="932" alt="Screen Shot 2022-11-11 at 8 26 02 AM" src="https://user-images.githubusercontent.com/24623109/201372070-af9e8ef7-d7f6-4330-939e-874a4162b14c.png">

**Comment by bartreardon** [comment]
@dan-snelson 
![image](https://user-images.githubusercontent.com/3598965/201450144-2618c5f3-f19b-4d7b-b6ee-e6d6333cf61b.png)

**Comment by dan-snelson** [comment]
More 🥓, please!

(Closing as resolved.)
