### ISSUE TITLE
swiftDialog 2.0 RC1 - Notifications off by default

### ISSUE THREAD

**Issue by FogdogIT** [bartreardon/swiftDialog#187]
Installed pkg remotely via MDM. Installs fine and tests of dialog pop up work, but when I attempt to test the notification function. I get the following error in the terminal [screen attached as well]: 

`% /usr/local/bin/dialog --notification
Notifications are not available: Optional("Notifications are not allowed for this application")
`

![Screenshot 2022-11-11 at 09 36 23](https://user-images.githubusercontent.com/50748105/201312230-d1925a2f-6c4d-4ff9-b278-af867553fce0.png)

I have attempted to whitelist/enable notifications via mobileconfig profile using "au.bartreardon.dialog" as the bundleID, to no avail.

In my testing I also manually installed the pkg. When I do this, and then run the above command Dialog appears in the Sys Pref>Notification panel, and is disabled:

![Screenshot 2022-11-11 at 09 42 20](https://user-images.githubusercontent.com/50748105/201312607-d5058b61-87cb-46ff-aed1-5932a259d034.png)

Toggling the notifications on here, and then running the above command leads to the expected result. However, this is not feasible for mass deployment. 

Can you offer some guidance? I am not seeing a lot of documentation about this feature in your wiki (presuming as it is still RC). Thank you!

**Comment by bartreardon** [comment]
on the [release page](https://github.com/bartreardon/swiftDialog/releases/tag/v2.0RC1) there are a couple of mobileconfig profiles. One for if you want to set using banner style and one for alert style. Did you deploy one of those from your MDM?

Full documentation will be available when 2.0 is released

**Comment by FogdogIT** [comment]
Magical - that did the trick. Only wish I had seen before submitting this issue. Appreciate the fast response, coffee on its way to you!

On an aside, when I manually triggered the notification I did NOT receive a popup asking if I wanted to enable notifications - potential bug? Anyway, I now I have a mobileconfig file that is very much fit for purpose (using with https://github.com/SecondSonConsulting/Renew ) thanks again!

**Comment by bartreardon** [comment]
@FogdogIT can you take a look at this docco and let me know what you think? https://github.com/bartreardon/swiftDialog/wiki/Notifications#updating-the-default-notification-icon

**Comment by fogdogit-paul-s** [comment]
Hey Bart - replying to this with my personal acct. Just tested the above and it worked like a charm! Thank you!

![Screenshot 2022-11-16 at 15 11 43](https://user-images.githubusercontent.com/118294164/202218855-affbc711-7a6e-4557-ae5d-42e289e86a7d.png)
