### ISSUE TITLE
Allow list to be selectable

### ISSUE THREAD

**Issue by joncrain** [bartreardon/swiftDialog#191]
As an alternative to #108, I would like to propose adding the ability to have a list be selectable. The idea would be to keep the formatting and look of the checkboxes to mirror the list:

i.e. move this: 
![image](https://user-images.githubusercontent.com/5123982/201698314-ad14adc1-c88b-470a-b053-36b9ca9c0a38.png)

to something like this:
![image](https://user-images.githubusercontent.com/5123982/201699430-6010a0a2-8f86-44bb-b301-26a472e3bef6.png)

This would allow us to put more options in the checkbox list and allow for better formatting.

**Comment by mm2270** [comment]
👍 
This gets my vote. That mock up looks nice. I'd love to be able to use something like that for some of my scripts.

**Comment by remcoverburgh** [comment]
This is indeed a feature which would be nice to have.

**Comment by joncrain** [comment]
2.2 Preview 1 has a checkbox style option that satisfies this 99% of the way. Just need to add the [scrolling](https://github.com/bartreardon/swiftDialog/issues/256) to it.

**Comment by bartreardon** [comment]
Closing this as done. Using the `switch` style to allow an arbitrary list of items in a scrollview will be the recommended method for managing bulk selectable options. 

Some enhancements in [2.3](https://github.com/bartreardon/swiftDialog/releases/tag/v2.3.0) helps with presentation and performance.
