### ISSUE TITLE
Feature Request: Allow message text in addition to an image in a dialog

### ISSUE THREAD

**Issue by mm2270** [bartreardon/swiftDialog#194]
I would like to be able to add both an image _**and**_ message text to a dialog. Right now, Dialog really only allows for message text _**or**_ an image. While an image can have an image description below it, it's not very efficient if you want to display more text below or above the image. It seems limited in what that image description can show.

While I'm at it, if this feature is added, a bonus would be the ability to specify what order the text or image should appear in. For example, message above the image, or image above the message. This would allow for some nice flexibility in creating dialogs.

**Comment by bartreardon** [comment]
ordering is more complicated than just having image + message capability.

You can have images in a dialog now though  as long as they are from a http(s) source by adding in the image with markdown, e.g.
`dialog --message "Message before  \n\![test image](https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Test.svg/631px-Test.svg.png)  \nMessage After"`

**Comment by mm2270** [comment]
Hi @bartreardon Thanks for the reply on this.
Your comment gave me the idea of possibly using a local image path in the Markdown code, but as was already reported in Issue #196 this doesn't work. I'm hoping there is some way in the future to add this, or, maybe a way to have `--message` be an available option when also using `--image`, which, while possibly not as flexible as doing it in Markdown, would still be a nice enhancement.

**Comment by bartreardon** [comment]
added in [2.3](https://github.com/bartreardon/swiftDialog/releases/tag/v2.3.0) (see release notes)

images appear above the message. If you want images below or inline then you'll still need to use markdown inline image notation and host your images somewhere.
