### ISSUE TITLE
--messagealignment , --alignment arguments not recognizing center, only centre

### ISSUE THREAD

**Issue by Tribruin** [bartreardon/swiftDialog#195]
I am testing 2.0 with a project I am writing and am finding that the --alignment/--messagealignment options are not recognizing  "center" option, only "centre"

Examples
` dialog --title "Test" --message "This is test message" --messagealignment center --messageposition center --ontop`

Gives this dialog
<img width="888" alt="Screen Shot 2022-11-17 at 11 30 38 AM" src="https://user-images.githubusercontent.com/39201800/202542947-61b1f7db-5a00-452e-832b-6ae61dd42e22.png">

`dialog --title "Test" --message "This is test message" --messagealignment centre --messageposition centre --ontop`
<img width="932" alt="Screen Shot 2022-11-17 at 1 39 10 PM" src="https://user-images.githubusercontent.com/39201800/202543105-dbaede4a-67ae-464d-a33d-4da022915c04.png">

**Comment by elliotnev27** [comment]
+1 same results on MacOS 12.6.1; SwiftDialog v2.0.3810
