### ISSUE TITLE
Feature Request: Disable Mission Control when using `blurscreen`

### ISSUE THREAD

**Issue by dan-snelson** [bartreardon/swiftDialog#198]
Please see [Setup Your Mac Issue No. 16](https://github.com/dan-snelson/dialog-scripts/issues/16).

Is it even possible to disable Mission Control?

**Comment by bartreardon** [comment]
not when displaying a window like that.

It may be possible, e.g. fullscreen mode will ignore any commands to open mission control but it's a complete fullscreen window, not a non-fullscreen window with another "as big as the screen" window behind it.

You have to accept that at some point that as an app you are at the whims of the OS

**Comment by dan-snelson** [comment]
Thanks, Bart.
