### ISSUE TITLE
Video service playback results in "player error" when executed outside of logged-in user context

### ISSUE THREAD

**Issue by dan-snelson** [bartreardon/swiftDialog#203]
With swiftDialog `2.0.1.3814`, video playback using Vimeo or YouTube produce an error if executed as `root`.

(Local video files work as expected when executed as `root`.)

## Logged-in User: Works as Expected
`dialog --title "Logged-in User: Vimeo works as expected" --video vimeoid=774283815 --autoplay`
<img width="1012" alt="Screen Shot 2022-12-05 at 5 32 17 AM" src="https://user-images.githubusercontent.com/24623109/205638121-da438c8c-2f14-47fa-82a2-c7b823c28285.png">

`dialog --title "Logged-in User: YouTube works as expected" --video youtubeid=IHQaI54D_u4 --autoplay`
<img width="1012" alt="Screen Shot 2022-12-05 at 5 33 38 AM" src="https://user-images.githubusercontent.com/24623109/205638385-b6f954d6-6790-4c46-af42-0cd7500a3038.png">

---

## Root: Local file works as expected
`sudo -i`

`dialog --title "root: Local video file works as expected" --video /Users/dan/Movies/Screencasts/Edited/Setup\ Your\ Mac\ \(1.5.0\).mp4`
<img width="1012" alt="Screen Shot 2022-12-05 at 5 38 53 AM" src="https://user-images.githubusercontent.com/24623109/205639463-18e46804-b865-48ea-8cd1-6e5aa91b309f.png">

---

## Root: Player Error
`sudo -i`

`dialog --title "root: Vimeo player error" --video vimeoid=774283815 --autoplay`
<img width="1012" alt="Screen Shot 2022-12-05 at 5 35 24 AM" src="https://user-images.githubusercontent.com/24623109/205638711-b61ebc41-7836-4c72-82eb-16cbc4384d24.png">

`dialog --title "root: YouTube An error occurred" --video youtubeid=IHQaI54D_u4 --autoplay`
<img width="1012" alt="Screen Shot 2022-12-05 at 5 36 18 AM" src="https://user-images.githubusercontent.com/24623109/205638887-2e17fe1b-ebea-4dd6-aa39-fefdf8e845fe.png">

**Comment by bartreardon** [comment]
This is one of those things where running a gui application as root has weird consequences.

To resolve this, I'm going to update `/usr/local/bin/dialog` to the following code:

```bash
#!/bin/sh
currentUser=$(echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ { print $3 }')
if [ "$currentUser" = "loginwindow" ]; then
    echo "Cannot run at loginwindow"
    exit
fi
if [ $(id -u) -eq 0 ]; then
    sudo -u $currentUser /Library/Application\ Support/Dialog/Dialog.app/Contents/MacOS/Dialog "$@"
else
    /Library/Application\ Support/Dialog/Dialog.app/Contents/MacOS/Dialog "$@"
fi
```

this will then should always run fine (including fix issues with language and colour accent preferences)

**Comment by dan-snelson** [comment]
Thanks, @bartreardon.

**Comment by dan-snelson** [comment]
In a singled test of swiftDialog version `2.1.0.3924`, swapping the following two lines allowed playback as expected: 
https://github.com/dan-snelson/dialog-scripts/blob/main/Setup%20Your%20Mac/Introduction-to-Setup-Your-Mac.bash#L301-L302

However, I did observe — but haven't troubleshooted — the following error:

`Error: You don’t have permission to save the file “dialogCommandFile.OaA” in the folder “tmp”.`

**Comment by bartreardon** [comment]
yeah, I'm working on fixing that in `/usr/local/bin/dialog` by chowning the command file on the fly

**Comment by bartreardon** [comment]
update `/usr/local/bin/dialog` with the following and LMK if it works for you.

```bash
#!/bin/sh
currentUser=$(echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ { print $3 }')
dialogpath="/Library/Application Support/Dialog/Dialog.app"
dialogbin="$dialogpath/Contents/MacOS/Dialog"
commandfile=$(echo "$@" | awk -v pattern="--commandfile" '{for (i=0;i<=NF;i++) {if ($i==pattern) print $(i+1) }}')

# Check to make sure we have a binary to run
if [ ! -e "$dialogbin" ]; then
    echo "Cannot find swiftDialog binary at $dialogbin"
    exit 255
fi

# check we have a valid console user
if [ "$currentUser" = "loginwindow" ] || [ -z $currentUser ]; then
    echo "Cannot run. No console user, or at loginwindow."
    exit 255
fi

# If we're running as root, launch swiftDialog as the user.
if [ $(id -u) -eq 0 ]; then
    if [ ! -z $commandfile ]; then
        # a command file is being used - make sure the console user has write access to it.
        touch "$commandfile"
        chmod 644 "$commandfile"
    fi
    sudo -u $currentUser "$dialogbin" "$@"
else
    "$dialogbin" "$@"
fi
```

**Comment by dan-snelson** [comment]
@bartreardon:

Should this be working as `root` with `2.1.0.4035`, or, do we need to run the command as the logged-in user?

```
root# dialog --version
2.1.0.4035

root# dialog --title "root: Vimeo player test" --video vimeoid=782138075 --autoplay
```

<img width="1012" alt="Screenshot 2023-01-18 at 5 28 28 PM" src="https://user-images.githubusercontent.com/24623109/213327476-75e301eb-c851-4da0-9abd-21900cb422d2.png">

**Comment by dan-snelson** [comment]
This is working, but I had to first revert permissions on `/usr/local/bin/dialog` to `777` from our preferred:

```
ls -lah /usr/local/bin/dialog
-rwxr--r--  1 root  wheel    86B May 30  2022 /usr/local/bin/dialog
```

I pasted the following commands in Terminal, after having elevated to `root` …

```
loggedInUser=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ { print $3 }' )

if [[ -z "${loggedInUser}" || "${loggedInUser}" == "loginwindow" ]]; then
    echo "No user logged-in; exiting."
    exit 1
else
    loggedInUserID=$(id -u "${loggedInUser}")
fi

function runAsUser() {

    echo "Run \"$@\" as \"$loggedInUserID\" … "
    launchctl asuser "$loggedInUserID" sudo -u "$loggedInUser" "$@"

}
```

… then attempted to play the video:

```
root# runAsUser dialog --title "root > logged-in user Vimeo player test" --video vimeoid=782138075 --autoplay
Run "dialog --title root: Vimeo player test --video vimeoid=782138075 --autoplay" as "503" … 
sudo: unable to execute /usr/local/bin/dialog: Permission denied

Macs-MacBook-Air:~ root# chmod -v 777 /usr/local/bin/dialog 
/usr/local/bin/dialog

root# runAsUser dialog --title "root > logged-in user Vimeo player test" --video vimeoid=782138075 --autoplay

Run "dialog --title root > logged-in user Vimeo player test --video vimeoid=782138075 --autoplay" as "503" … 
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
```

<img width="1012" alt="Screenshot 2023-01-18 at 5 33 38 PM" src="https://user-images.githubusercontent.com/24623109/213328596-0bda10d1-514c-47de-a26c-2554e29345d0.png">

**Comment by bartreardon** [comment]
```
ls -la $(which dialog)
-rwxr-xr-x@ 1 root  wheel  1030 12 Dec 17:59 /usr/local/bin/dialog
```

with this setup `sudo dialog --title "root > logged-in user Vimeo player test" --video vimeoid=782138075 --autoplay` works as extected, no need to change permissions to 777, which would be highly insecure anyway as it gives a non root user read write access to  a script that is executed  (potentially) as root.

the provisions in the updated `/usr/local/bin/dialog` should handle the running as and whathaveyou, no need for your own runas function

**Comment by dan-snelson** [comment]
Thanks, Bart.

Confirming the issue is on my end; closing.
