### ISSUE TITLE
Cannot change the image in a running dialog

### ISSUE THREAD

**Issue by BigMacAdmin** [bartreardon/swiftDialog#205]
`echo "image: /path/to/image.png" >> /var/tmp/dialog.log` 
This is not currently working to update the image in an already running dialog.

v2.0.1.3814, but @smithjw states they are getting the same issue in v1.11 and v2.0

**Comment by smithjw** [comment]
Just to update this issue...

I have narrowed down the issue to changes between `2.0` and `1.11.2`. When sending `image:` in the command file to add or change an image, swiftDialog does nothing and does not update an image in 2.0. On 1.11.2 and below, each time `image:` is added into the command file, swiftDialog will display the relevant image.

Additionally in the 2.0 releases, when using the `--image` command line option to initially launch the swiftDialog window, sending a subsequent `message:` or `list:` into the command file, swiftDialog will still display the initial image and not the messages/lists. In 1.11.2 sending these updates to the command file would result in the image being dismissed and relevant content shown.

**Comment by bartreardon** [comment]
casualty of the re-write. was writing the image info to the wrong location.

**Comment by BigMacAdmin** [comment]
Quick testing of this in v2.1.0.4009:

```
/usr/local/bin/dialog --image "/path/to/image1.png" &
sleep 3
echo "image: /path/to/image2.png" >> /var/tmp/dialog.log
```

this results in the image being added to the "carousel" , where I expected it to _replace_ the image in the original dialog. When the image is added to the "carousel", it is not automatically made the "active" image either.

Is my expectation incorrect, or is the behavior incorrect?

**Comment by bartreardon** [comment]
that' the current behaviour yes - each `image:` command adds an image to the carousel.

If you'd like to update in place that is currently not possible but sounds like a great FR

**Comment by BigMacAdmin** [comment]
Thanks, then this issue appears resolved in the new beta, and I'll open a new issue with a feature request.

**Comment by bartreardon** [comment]
happy to FR based off this issue 🙂

**Comment by bartreardon** [comment]
initial playing I can add "show" "hide" "clear" commands easily - that preserves existing behaviour but will require you to do a "clear" before adding a new image - I'll have a think about combinations or something like "image: replace: /some/image.png"

**Comment by smithjw** [comment]
Adding a hide/clear before the replaced image works for me.
________________________________

**Comment by bartreardon** [comment]
cool - I'll close this and any ongoing discussion can go in #216
