### ISSUE TITLE
swiftDialog forces en-US keyboard layout for text input

### ISSUE THREAD

**Issue by conscia-tjk** [bartreardon/swiftDialog#206]
When I make a box with text input, it ignores the keyboard layout set by the system.
So if my keyboard language is danish, it will the text as if the keyboard was en-US format which makes passwords complicated to enter, if the text box is set as secure so the input changes to ***

![Screenshot 2022-12-09 at 12 09 10](https://user-images.githubusercontent.com/118997331/206689341-4a697c6a-439d-4598-b90a-a283f0fdfa9b.png)
I'm entering "___@@@" and gets the result as above

I'm using v2.0.1

**Comment by bartreardon** [comment]
Is your process that launches swiftdialog running as root? If so it will use the keyboard scheme set for the root user, which will probably be en-us. What happens when you run as your own account? swiftDialog uses standard SwiftUI textfields and should respect your user settings.

**Comment by conscia-tjk** [comment]
If I run the script without sudo it works as you say, but then the rest of my script doesn't work

It's a script pushed out with MDM and it needs to run with root privileges for the other commands it's doing. Can I start the dialog windows as the user while the script is running as root?

**Comment by bartreardon** [comment]
Yup. Use the `sudo -u` method described here to run swiftDialog as the current user 
https://scriptingosx.com/2020/08/running-a-command-as-another-user/

**Comment by bartreardon** [comment]
So this lead me down a rabbit hole but in short, yes, it's possible to launch using the users language and highlight preferences without launching dialog itself in the user context.

The following will determine the language and highlight color and launch with the user specified values.

```bash
#!/bin/zsh
if [ $(id -u) -eq 0 ]; then
    currentUser=$(echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ { print $3 }')
    language=$(sudo -u $currentUser /usr/bin/osascript -e 'return user locale of (get system info)')
    accentColor=$(sudo -u $currentUser defaults read -g AppleAccentColor)
    if [ $? -ne 0 ]; then
        # nil result, default to blue
        accentColor=4 
    fi
    # launch in the users language
    /Library/Application\ Support/Dialog/Dialog.app/Contents/MacOS/Dialog "$@" -AppleLanguages "($language)" -AppleAccentColor $accentColor
else
    /Library/Application\ Support/Dialog/Dialog.app/Contents/MacOS/Dialog "$@"
fi
```

**Comment by mm2270** [comment]
I wasn't even aware that `-AppleLanguages` and `-AppleAccentColor` were flags that could be used with swiftDialog. Is that in the main documentation? If so, I missed it. This could be useful. Thanks for pointing it out anyway.

**Comment by mm2270** [comment]
Hi @bartreardon Couple of questions on this. How do we get this to work (the use of `-AppleAccentColor` etc.) when displaying a dialog that uses a generated json file as the source? I can't seem to get that to work. It works ok when calling Dialog and using direct command line arguments, but not if I tell it to use a json file. I get an error that states something like:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString count]: unrecognized selector sent to instance 0x600002d4af40'
```
Any thoughts on this?

Second, I took a scan thru the documentation and I don't see a mention of these flags, though it's not impossible I just missed it, or I'm looking in the wrong location. If they aren't added, you might want to add them at some point so people are aware of them. Thanks!

**Comment by bartreardon** [comment]
@mm2270  those flags aren't documented. They are actually macOS flags that can be used on any application, that said I've gone off using them because of potential issues.

Instead I will be including this as the `/usr/local/bin/dialog` launcher which will run swiftDialog as the current logged in user (only catch with this is the location of `--commandfile` if used can't use a path with a space in it.....yet):

```bash
#!/bin/sh
currentUser=$(echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ { print $3 }')
dialogpath="/Library/Application Support/Dialog/Dialog.app"
dialogbin="$dialogpath/Contents/MacOS/Dialog"
commandfile=$(echo "$@" | awk -v pattern="--commandfile" '{for (i=0;i<=NF;i++) {if ($i==pattern) print $(i+1) }}')
​
# Check to make sure we have a binary to run
if [ ! -e "$dialogbin" ]; then
    echo "Cannot find swiftDialog binary at $dialogbin"
    exit 255
fi
​
# check we have a valid console user
if [ "$currentUser" = "loginwindow" ] || [ -z $currentUser ]; then
    echo "Cannot run. No console user, or at loginwindow."
    exit 255
fi
​
# If we're running as root, launch swiftDialog as the user.
if [ $(id -u) -eq 0 ]; then
    if [ ! -z $commandfile ]; then
        # a command file is being used - make sure the console user has write access to it.
        touch "$commandfile"
        chmod 644 "$commandfile"
    fi
    sudo -u $currentUser "$dialogbin" "$@"
else
    "$dialogbin" "$@"
fi
```
