### ISSUE TITLE
Textfield does not handle quotation marks well

### ISSUE THREAD

**Issue by TobyFenna** [bartreardon/swiftDialog#207]
If a quotation mark is included in a string when using the --textfield option Dialog will omit the quotation mark.

Example:
`/usr/local/bin/dialog --textfield "Enter string"`

String entered: 
> Show me those " quotes "

Dialog output:
> Show me those  quotes 

A workaround has been found by using the --json flag. Though this then requires the output to be parsed in order for it to be usable in most applications.

Example with --json flag:
`/usr/local/bin/dialog --textfield "Enter string" --json | grep "Enter string" | awk -F " : " '{print $NF}' | sed 's/^.\(.*\).$/\1/' | sed -r 's/[\"]+/"/g'`

Piping to JQ using `jq -r` is much cleaner, although it is not ideal to have to deploy JQ to a fleet of Macs.

While we can use this workaround, perhaps an enhancement could be made so we can avoid having to use JSON and piping to sed.

Further context in [Slack](https://macadmins.slack.com/archives/C01U5MXNGG6/p1670418252494049).

**Comment by BigMacAdmin** [comment]
Unfortunately, I found a problem with your workaround.

If the user enters a `\` character, or even multiple `\\\\\`, it will be replaced with a single `"` character.

**Comment by bartreardon** [comment]
I don't know why but the code for printing out the values explicitly strips `"` from the output. The commit for that line doesn't say why but I can't see an obvious reason why I would have done that.
