### ISSUE TITLE
Feature Request: Enhance behavior when adding images to a running dialog

### ISSUE THREAD

**Issue by BigMacAdmin** [bartreardon/swiftDialog#216]
Currently, if an image is added to an already running dialog that image is added onto the "pile" or the "carousel" of images already present in that dialog window.

Please consider an enhancement which would allow us to _replace_ images in a running dialog window, instead of adding onto the carousel. This could perhaps come as a single new action that does the replacement, or a single new action that removes the existing images, or both separately.

**Comment by bartreardon** [comment]
Discussion from #205 to be continued here

**Comment by bartreardon** [comment]
https://github.com/bartreardon/swiftDialog/issues/205#issuecomment-1372961763
> initial playing I can add "show" "hide" "clear" commands easily - that preserves existing behaviour but will require you to do a "clear" before adding a new image - I'll have a think about combinations or something like "image: replace: /some/image.png"

**Comment by bartreardon** [comment]
Should be addressed in the latest release - LMK if it's not
