### ISSUE TITLE
swiftDialog `2.1.0-4009` not updating `progresstext`

### ISSUE THREAD

**Issue by dan-snelson** [bartreardon/swiftDialog#218]
When testing [Setup Your Mac (1.6.0-rc12)](https://github.com/dan-snelson/dialog-scripts/blob/issue-21/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash) with swiftDialog `2.1.0-4009`, `progresstext` does not update as expected.
<img width="932" alt="Screenshot 2023-01-06 at 8 03 00 AM" src="https://user-images.githubusercontent.com/24623109/211043087-edbf05e8-1e94-4378-a0e4-4f7cee5d88f3.png">

When testing the same script with swiftDialog `2.0.1-3814`, `progresstext` is updated as expected.
<img width="932" alt="Screenshot 2023-01-06 at 8 00 55 AM" src="https://user-images.githubusercontent.com/24623109/211043241-8768a851-18c0-4d50-9632-dda48dd42df5.png">

(Perhaps this is due to the fact that, currently, all the [Command Files](https://github.com/dan-snelson/dialog-scripts/blob/issue-21/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L123-L125) are owned by `root`.)

**Comment by colorenz** [comment]
Do you think it's because of the Command Files? Swiftdialog is also executed by root and should read them?

**Comment by dan-snelson** [comment]
Just a hunch, @colorenz; I'll defer to @bartreardon.

**Comment by dan-snelson** [comment]
@bartreardon: In a single test, this issue appears to be resolved in `2.1.0.4035`.

<img width="932" alt="Screenshot 2023-01-18 at 5 16 13 PM" src="https://user-images.githubusercontent.com/24623109/213326393-ecb21ae4-3d41-4429-8da2-d92979e88034.png">

Thanks!
