### ISSUE TITLE
dialog with --progress

### ISSUE THREAD

**Issue by shannonpasto** [bartreardon/swiftDialog#220]
Hi.

When starting dialog with --progress it'd be nice to see the progress bar start with a "side to side"  animation while waiting for the first progress command in the command file, at which point it can then begin it's move from left to right as you progress with each subsequent progress command. I hope I've explained that correctly. I like this in DEPNotify but am wanting to move to dialog for onboarding as there are a lot more features available.

Alternatively, a way to start/display the progress bar after calling dialog (without --progress) via the command file.

Cheers,
Shannon

**Comment by bartreardon** [comment]
does it not do that? - it should

**Comment by bartreardon** [comment]
crap - it's not doing it - wonder when that stopped working - generally on launch it should go into indeterminate mode (run `dialog --mini --progress` to see how it should look)

**Comment by BigMacAdmin** [comment]
This is working for me on version `2.0.1.3814`

I whipped up this example, it seems to do exactly what @shannonpasto is asking for.

https://github.com/SecondSonConsulting/swiftDialogExamples/blob/main/progressExample.sh

**Comment by BigMacAdmin** [comment]
I upgraded to `2.1.0.4035` and ran the same script I linked above.

The progress bar worked, however `progresstext:` commands did not. No progress text was shown.

**Comment by bartreardon** [comment]
worked here 
`echo "progresstext: Test" >> /var/tmp/dialog.log`

![image](https://user-images.githubusercontent.com/3598965/214499257-5c68e15f-93d1-47f5-893b-ccd9e65557e4.png)

**Comment by bartreardon** [comment]
the bouncy progress bar is not though....  :/

**Comment by BigMacAdmin** [comment]
In full size window, the bouncy bar does not work.

In `--mini` window, progresstext doesn't work

**Comment by shannonpasto** [comment]
I can confirm that with --mini it works, without --mini it does not. using version 2.1.0.4035

**Comment by bartreardon** [comment]
weird - I have the opposite - works in `--mini` not in the normal size

**Comment by bartreardon** [comment]
ok - cool, a bug I can replicate - I'll be back

**Comment by BigMacAdmin** [comment]
@shannonpasto if you use the latest stable release, this is working as intended and behaves how you've requested

**Comment by shannonpasto** [comment]
Thanks. I'm using the RC due to a feature in it that you've added

**Comment by bartreardon** [comment]
Try this build and let me know what you think.

bonus feature - `progress: reset` should return the indeterminate view

[dialog-2.1.0-4084.pkg.zip](https://github.com/bartreardon/swiftDialog/files/10506515/dialog-2.1.0-4084.pkg.zip)

**Comment by shannonpasto** [comment]
Yup, all working including. Starts intermediate on launch, progresses with integer, changes text as well. The new feature works as well.

Did the same tests with `--mini` and all working there as well.

Thanks for fixing

**Comment by BigMacAdmin** [comment]
I ran all of my projects and example scripts through this, and tried to break it like I did the last build, and I had no issues. You are a champion.

**Comment by shannonpasto** [comment]
Just tested RC3 and everything looks good with my script. All the bonus and extra features work as well!

Cheers,
Shannon
