### ISSUE TITLE
Bring Dialog on top of all windows via command file

### ISSUE THREAD

**Issue by martinvandiemen** [bartreardon/swiftDialog#221]
I would like to bring Dialog on top of all windows. During an installation Dialog can dissapear in the background. To make if visible to the user again I would like that the commandfile accepts the command "ontop" to bring it on top.

Example:
`$ echo "ontop: true" >> /var/tmp/dialog.log`

**Comment by bartreardon** [comment]
I can add that to a future release.

In the meantime, you can achieve this with `/usr/bin/osascript -e 'tell application "Dialog" to activate'`
