### ISSUE TITLE
Feature Request: Ability to update the --progress setting dynamically

### ISSUE THREAD

**Issue by wakco** [bartreardon/swiftDialog#225]
That is, to be able to change the total number of increments set by `--progress` from within the dialog command file, to allow for a script that might discover that it has more steps to go through than were initially available.

Yes this is another DEPNotify can do this with the Determinate command, but I've yet to find out how to get swiftDialog to do it (I've checked the wiki).

**Comment by bartreardon** [comment]
yeah currently not implememted. Whatever steps you define at launch is what you are stuck with.

That said, the progress value you send is a double value, not an integer, so you could initiate with `dialog --progress 1` and the command `echo "progress: 0.1" >> /var/tmp/dialog.log` would increment the bar by 10% of the distance.

the default value is 100, so you can work out your steps as a percentage and then `echo "progress: increment ${single_step_value}" >> /var/tmp/dialog.log` 
You can then reset with `echo "progress: reset" >> /var/tmp/dialog.log`, work out your new step increment value and go again.

**Comment by wakco** [comment]
Thanks, good to know, I'll see what I can script to treat it as a percentage (%) in the meantime.
