### ISSUE TITLE
Feature Request: Deactivate buttons for a defined time until clickable

### ISSUE THREAD

**Issue by opus-nbo** [bartreardon/swiftDialog#231]
We all know it:

1. Users see a dialog popping up
2. User does not read the message and instantly clicks the next reachable button
3. Goal failed

I propose a feature to define a timespan in which buttons are not clickable (greyed out) when a dialog is displayed. After the timespan has passed, the button becomes clickable. Either this could be defined for the whole dialog or for individual buttons.

Optional: A timer that displays the time in seconds until a button gets clickable.

Let me know what you think about my idea.

**Comment by bartreardon** [comment]
this is already possible. Three ways to do it:

## Option 1 - using `--timer`

`dialog --timer 10`

will show a timer for 10 seconds. When the time is up the dialog will be dismissed automatically

<img width="932" alt="image" src="https://user-images.githubusercontent.com/3598965/219316392-2767d446-634b-4e83-b160-eb9c2f1b810e.png">

## Option 2 - using `--timer` and show a dismissal button

`dialog --button1text "Please Wait" --button1disabled --timer 10`

will show a timer for 10 seconds. After three seconds, the button becomes enabled and the user can press the button. When the time is up the dialog will be dismissed automatically

<img width="932" alt="image" src="https://user-images.githubusercontent.com/3598965/219314130-288ed493-26bf-4e88-ae10-3b9faf553f70.png">


## Option 3 - using `--progress`

`dialog --button1text "Please Wait" --button1disabled --progress 10 & for i in {0..10}; do echo "progress: $i" >> /var/tmp/dialog.log; echo "progresstext: Timeout in $((10 - $i)) seconds" >> /var/tmp/dialog.log; sleep 1; done; echo "button1: enable" >> /var/tmp/dialog.log`

will show a progress bar and countdown for 10 seconds after which button 1 is enabled. It's up to the user to dismiss the button.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/3598965/219315102-13614c2b-29ab-45d5-af79-e48d3279a605.png">

(written in long form)

```bash
dialog --button1text "Please Wait" --button1disabled --progress 10 &

for i in {0..10}; do
  echo "progress: $i" >> /var/tmp/dialog.log
  echo "progresstext: Timeout in $((10 - $i)) seconds" >> /var/tmp/dialog.log
  sleep 1
done
echo "button1: enable" >> /var/tmp/dialog.log
```

[using the command file](https://github.com/bartreardon/swiftDialog/wiki/Updating-Dialog-with-new-content) offers a lot more flexibility in what you are wanting to achieve. You could send your own command to quit the dialog, enable buttons, update progress etc.

**Comment by bartreardon** [comment]
You can do whatever logic you want that you're capable of scripting. swiftDialog is just a dumb UI for presenting information that you can update on the fly from a bash script or whathaveyou. How you use it is up to you.

**Comment by Tribruin** [comment]
I do something to create a countdown in the button itself:

```
while [[ countdown -gt 0 ]]; do
    sleep 1
    countdown=$(( countdown - 1 ))
    echo "button1text: Ok (${countdown})" >> "$dialogLog"
  done
  /bin/echo "quit:" >> "$dialogLog"
```

It counts down and updates the button text. You could disable the button, use this code to update the button text, and then enable the button at that end. For me, I just quit Dialog when the countdown ends, so the user doesn't leave the dialog up and running in the background.
