### ISSUE TITLE
Support for installing first time via a script

### ISSUE THREAD

**Issue by charliwest** [bartreardon/swiftDialog#232]
Would it be possible to get the versioning on the release in line as in 2.1.0 is actually 2.1.0-4148?

This way we could initially deploy using something like Nudge has https://github.com/rs1278/macOSinstallers/tree/main/Installers/Nudge

**Comment by acodega** [comment]
I don't think it needs to be that strict. If you simply want to install the latest version, [you can use my script function](https://github.com/acodega/dialog-scripts/blob/main/dialogCheckFunction.sh). It includes a verification of the team ID which adds additional protection and ensures the pkg download was complete.

If you want a script to update swiftDialog if its out of date, you can curl the GitHub URL and cut the version out, ie `curl -sLI "https://github.com/bartreardon/swiftdialog/releases/latest" | grep -i "^location" | tr "/" "\n" | tail -1 | sed 's/[^0-9\.]//g'` and compare it to the pkg receipt version that's on the Mac. `pkgutil --pkg-info-plist au.csiro.dialogcli 2>/dev/null | grep -A 1 pkg-version | tail -1 | sed -E 's/.*>([0-9.]*)<.*/\1/g'`

This is all bits I've stolen [from Installomator](https://github.com/Installomator/Installomator).

**Comment by scriptingosx** [comment]
[Installomator](https://github.com/Installomator/Installomator) has no problem with the Swift Dialog versioning

**Comment by charliwest** [comment]
Fair enough, cheers guys!
