### ISSUE TITLE
Failure behavior with empty arguments

### ISSUE THREAD

**Issue by adem-kfs** [bartreardon/swiftDialog#237]
Several arguments that expect more info fail in different ways when no info is actually provided, vs being ignored, reverting to defaults or failing with a meaningful error.

Fails with `uncaught exception 'NSInvalidArgument'`:
`--commandfile`

Fails with `Illegal instruction`:
`--image`
`--imagecaption`
`-n`
`--bannerimage`
`--selectvalues`
`--selectvalues <values> --selectdefault`
`--checkbox`
`--listitem`
`-bg`
`--background`
`--jsonfile`

Causes binary to hang:
`--height`
`--width`

**Comment by bartreardon** [comment]
correct - it's up to the admin implementing swiftDialog into their scripts to ensure it's operating as they expect.
