### ISSUE TITLE
Feature Request: Add "fallback" icons for `--overlayicon` `--bannerimage` and other file path arguments

### ISSUE THREAD

**Issue by BigMacAdmin** [bartreardon/swiftDialog#239]
Currently, if one specifies a file that doesn't exist for `--icon` a "fallback" icon is used instead. This is a great feature, and I would like to see the same behavior added for other features like `--overlayicon` `--bannerimage` `--background` etc.

I'm weighing the need to code some kind of validation myself for Baseline, because currently if an admin specifies an invalid `--overlayicon` in their options then the script fails in a bad way.

Alternatively, if this isn't something you wish to add, can you clarify or specify for me if a specific exit code is used for all/each of these?

**Comment by BigMacAdmin** [comment]
Testing this further, it looks like the "fail" condition is happening when a directory is given as a filepath. The exit code is `201` with the error `ERROR: Image resource cannot be found : /path/to/dir`

Would it be possible to use the fallback icon in this situation instead of failing the dialog window altogether? My preference would be for the error message to remain in order to indicate the issue but it would not cause an outright failure.

**Comment by bartreardon** [comment]
how's this look?

<img width="932" alt="image" src="https://user-images.githubusercontent.com/3598965/232948685-9d08660d-1312-46d3-ad8a-b7da23ff859f.png">

regarding an error image for the overlay icon, the default behaviour is that if there's an issue is just doesn't show. I took this approach rather than display an error icon as a safe fallback. Open to suggestions though.

**Comment by dan-snelson** [comment]
As this is @BigMacAdmin’s FR, I’ll defer to Trevor, but my two cents are `bannerimage` looks good.

For `overlayicon`, one advantage of **having** an error image is that you know something _should_ be displaying and that your filepath is wrong.

**Comment by BigMacAdmin** [comment]
Looks good to me, Bart.

The problem I see with Dan's comment, is that currently --icon, --bannerimage, and --overlayicon all have different failure conditions. I think it would be nice if the dialog window didn't outright fail because an image was defined or downloaded as expected, personally.
