### ISSUE TITLE
Feature Request: Ability to make selectable lists required

### ISSUE THREAD

**Issue by hessorr** [bartreardon/swiftDialog#240]
--textfield has the optional parameter of making the field required. It would be great to also include this parameter on the selectable list menus so getting all types of input from the user is required before allowing the window to be closed. 

Thanks!

**Comment by bartreardon** [comment]
I presume this is different to using `--selectdefault` which will pre-set a selected value. It's up to the user to change it to something else but it does force a value.

**Comment by adorador** [comment]
+1.  I am in a similar situation as hessorr.  I would like to have an option for selectable lists to be required for a department list pull down.  We have 50+ departments, so we want to make sure that the customer selects their correct department before continuing.

**Comment by willriddick12** [comment]
Also looking to add a required setting for a selectable list.

**Comment by bartreardon** [comment]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/3598965/233076679-afdbcc0a-a4b5-4400-93f6-21a79e134ea5.png">

<img width="932" alt="image" src="https://user-images.githubusercontent.com/3598965/233076743-17797e96-952f-4f3f-b7f1-e704bedc2ffe.png">

**Comment by dan-snelson** [comment]
Yippee!

**Comment by adorador** [comment]
Exactly what I was looking for.  Thank you Bart!

**Comment by hessorr** [comment]
This is what I needed! Thank you so much!!
