### ISSUE TITLE
Feature Request: Ability to dynamically update Info Box with data

### ISSUE THREAD

**Issue by Lotusshaney** [bartreardon/swiftDialog#242]
--infobox make it possiable to turn this on and off in a preexisting dialog and also to have the text updatable from a command file.

This would allow for updtes like hostname, user name etc to be sent to the info box while the dialog is open.

**Comment by dan-snelson** [comment]
While I've never tried to "turn off" `--infobox`, with version `2.1.0.4148`, it's currently possible to update it.

**Comment by bartreardon** [comment]
`--infobox` is always there. whether it is "on" or "off" depends if there's is anything to show.

`echo "infobox: " >> /var/tmp/dialog.log`

will cause nothing to show

`echo "infobox: some text here  \\\n## A Heading\\\nAnd some **bold** text" >> /var/tmp/dialog.log`

will update the contents whether you launched dialog with and existing infobox or not.

**Comment by dan-snelson** [comment]
@bartreardon: I just noticed `infobox` isn't listed on the [Updating Dialog with new content](https://github.com/bartreardon/swiftDialog/wiki/Updating-Dialog-with-new-content) Wiki page.
