### ISSUE TITLE
Feature Request: set which input field has the focus

### ISSUE THREAD

**Issue by grahampugh** [bartreardon/swiftDialog#251]
Hi Bart, I don't know if this is possible, but I've had a [request](https://github.com/grahampugh/erase-install/issues/385) to apply the focus to a specific input field in a dialog when it appears. Specifically, in this example, the first field (username) is pre-filled, though overwritable when necessary, and ideally the second field (password) would have the cursor ready in it for input.

![228125661-567f5211-f207-46b2-9b2c-db2323f97064](https://user-images.githubusercontent.com/5802725/229881484-993ce3f9-dc2c-4869-b7d3-30877893441e.png)

Fine if it's not possible, I'm just passing on the message :-)

**Comment by bartreardon** [comment]
I've played with this for a bit and it will require swiftDialog to drop support for macOS 11.

That's not something I want to do at this time, at least it's not something I'm planning for the next release. This will have to wait until then.

**Comment by grahampugh** [comment]
Totally fair enough. macOS 11 support is pretty essential for erase-install anyway. Thanks for looking into it!
