### ISSUE TITLE
Problem Displaying Dialog on M2 Mac

### ISSUE THREAD

**Issue by Am0ri** [bartreardon/swiftDialog#252]
Hi there, I'm trying to use swiftDialog in Combination with Installomator and Jamf Pro. Did that according to this Guide https://github.com/Installomator/Installomator/tree/main/MDM/Jamf

When downloading an App via Self Service, the Dialog is presented perfectly on my Intel 16-Inch MacBook Pro from 2019. When I executed the same task on a M2 MacBook Air, the Dialog does not display. Nothing happens when I try to test dialog in my Terminal.

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/129986618/230163093-6299201d-7224-4671-ad4f-0ca07f89ab7e.png">

Im on Version: 2.1.0.4148
Any ideas on that? Thanks in advance

**Comment by bartreardon** [comment]
can you verify that you don't have a `/var/tmp/dialog.log` file that has a `quit:` command embedded in it?

**Comment by bartreardon** [comment]
am unable to replicate on any M2 device and am not getting any other reports from users on M2 devices. Closing this as it seems it's an errant `quit:` command in the `/var/tmp/dialog.log` file.
