### ISSUE TITLE
Checkbox switch style scroll issue

### ISSUE THREAD

**Issue by joncrain** [bartreardon/swiftDialog#256]
**Describe the bug**
When using the switch style with options that are greater than the height of the box, the display should switch to scroll like it does with lists.

**To Reproduce**
dialog --checkboxstyle "switch" --jsonfile ./json_data.json
```json
{
  "checkbox" : [
          {"label" : "Option 1", "checked" : true, "disabled" : true },
          {"label" : "Option 2", "checked" : true, "disabled" : false },
          {"label" : "Option 3", "checked" : false },
          {"label" : "Option 4", "checked" : true, "disabled" : true },
          {"label" : "Option 5" },
          {"label" : "Option 0" },
          {"label" : "Option 7" },
          {"label" : "Option 8" },
          {"label" : "Option 9" },
          {"label" : "Option 6", "disabled" : true }
        ]
}
```

**Expected behavior**
The list of checkboxes should scroll instead of taking all the window.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/5123982/234593394-42e4620d-c04c-4650-a253-b6deeaf86e30.png)

**Desktop (please complete the following information):**
 - macOS version 13.3.1
 - swiftDialog 2.2 preview 1

**Additional context**
Love this option! Thank you!

**Comment by bartreardon** [comment]
Thats not a new thing. Would do that with any long list of stuff user input related.

**Comment by joncrain** [comment]
Yeah, was debating on whether this is a bug or a feature request. I thought at some point the checkbox was scrollable, but I could be wrong on that. A normal message becomes scrollable when it exceeds the height of the box 🤷 so hopefully this is an easy thing to implement 🤞 

```sh
dialog --message "Test\n\nTest\n\nTest\n\nTest\n\nTest\n\nTest\n\nTest\n\nTest\n\nTest"
```

**Comment by bartreardon** [comment]
how's this look - only enabled when using "switch" checkbox style

https://user-images.githubusercontent.com/3598965/235443112-3bb9d0bf-599e-4a4b-97b4-641fd1c338ad.mov

**Comment by mm2270** [comment]
That looks great to me!

**Comment by bartreardon** [comment]
Thats because the message area is also in a scroll view and the height of the dialog is shared between them both. Add in `--messageposition top` to force all message content to the top and free up space for the rest of the content to render.

**Comment by joncrain** [comment]
This looks great! I would consider it a fix for #191 now as well.

![image](https://user-images.githubusercontent.com/5123982/236466786-9635404c-69c8-43b2-b56f-88f807fd4da0.png)

There seems to be one more small bug here, and it may just be how I'm holding it, but when pulling in a number of icon files, it seems that the loading of the dialog slows down and then does not get focus correctly and so the switches stay as gray (instead of the highlight color) which makes it a little confusing as to what is switched. I'm having trouble recreating consistently though, but basically it looks like this:

![image](https://user-images.githubusercontent.com/5123982/236471275-d020abb1-1300-4c03-baae-0816611ee63a.png)

and when you switch one it stays gray:
![image](https://user-images.githubusercontent.com/5123982/236471935-ea528af2-9558-4250-883b-18900c27b568.png)

You have to manually click to another app/Finder and back to see the colored switches. 
I've run the same command twice in a row and one time it did it, the next time it did not, which makes me think its a timing issue somewhere.

Here is the [json](https://gist.github.com/joncrain/42ef4ab6a3e17a67a3b33a47d6aae98a) I was testing with. Does not seem to be that way every time.

**Comment by bartreardon** [comment]
You are likely running into issues as you have many multiple labels with the same name. They should all be unique. Outside of testing this wouldn't happen (otherwise how would you know which label was checked and which one wasn't). Can you confirm this behaviour with a larger list of unique items?

**Comment by joncrain** [comment]
I noticed it first with unique items. I think probably around 12 with icons (web link) on all of them.

**Comment by bartreardon** [comment]
Just looking into this a bit. The image you're using in the example is 1200x1131 px which by itself isn't an issue as it will be just resized in the view, but it is overkill and given the number of repetitions explains the delay as it will download and prepare the image each time (not that an end user would notice). Why this is causing the window to display as if it were not the active window I'm not sure

In testing with a smaller image source I can reduce the instances where this happens though. For example using an image source from my jamfcloud instance (which is 512x512) I can almost never get this to occur.

**Comment by joncrain** [comment]
Originally the images I was using were 350x350 but seemed to take awhile to load (from our munki infra - s3). Not sure what’s going on!
