### ISSUE TITLE
New checkbox "switch" style problem when using json as source

### ISSUE THREAD

**Issue by mm2270** [bartreardon/swiftDialog#257]
**Describe the bug**
First off, thank you so much for the latest 2.2.0.4426 Preview build. I really love some of the enhancements and new features in this version.

I started playing around with the new "switch" checkbox style, as that's a really cool new addition, and I'm running into an inconsistency with it, depending it seems, on how it's initiated when calling Dialog.

What I'm finding is that if I craft a json string for just the checkboxes and call Dialog using regular shell command line flags and point it to the json for the checkboxes, I get the behavior I expect.
If on the other hand, I craft a full json file that has all the dialog attributes I want to display in it, and just point Dialog to that json file when it runs, the "switch" style for the checkboxes gets ignored.

**To Reproduce**
Take these 2 example scripts, which, technically I think should give me identical results, but they don't.

```
#!/bin/zsh

json_check='{
  "checkbox" : [
          {"label" : "Application One"},
          {"label" : "Application Two"},
          {"label" : "Application Three"},
        ]
}'

/bin/echo "$json_check" > "/var/tmp/check.json"

"/usr/local/bin/dialog" \
	--title "Selection Title" \
	--titlefont "name=SFProDisplay-Thin,size=21" \
	--message "This is the message" \
	--messagefont "size=14" \
	--icon "SF=arrow.down.circle.fill,weight=bold,color1=#38a7fc" \
	--iconsize "96" \
	--ontop \
	--button1text "Continue" \
	--button2text "Cancel" \
	--small \
	--checkboxstyle "switch,regular" \
	--jsonfile "/var/tmp/check.json"
```
The above gives me a dialog that looks like this.

![image](https://user-images.githubusercontent.com/3653600/234989092-24a9d8c7-68a4-4865-a671-2ffd9784fce6.png)

All good so far! I told it to use the switch style and my checkboxes show up as expected.

Now take this script, which calls dialog using a full json file with all the attributes and flags in it at one time.

```
#!/bin/zsh

json_source='{
	"title" : "Selection Title",
	"titlefont" : "name=SFProDisplay-Thin,size=21",
	"message" : "This is the message",
	"messagefont" : "size=14",
	"icon" : "SF=arrow.down.circle.fill,weight=bold,color1=#38a7fc",
	"iconsize" : "96",
	"ontop" : 1,
	"button1text" : "Continue",
	"button2text" : "Cancel",
	"small" : 1,
	"checkboxstyle" : "switch,regular",
	"checkbox" : [
    	{"label" : "Application One"},
        {"label" : "Application Two"},
        {"label" : "Application Three"},
	]
}'

/bin/echo "$json_source" > "/var/tmp/dialog.json"

/usr/local/bin/dialog --jsonfile "/var/tmp/dialog.json"
```

This gives me a Dialog that looks like this.

![image](https://user-images.githubusercontent.com/3653600/234989385-4d8b07c2-a1ef-44a5-8bc1-f2b68cd6f55b.png)

Meaning it instead gives me the older style checkboxes, ignoring the "checkboxstyle" flag, it seems.

Now, maybe I'm doing something wrong here, but with older versions of dialog, I've been able to use a similar method of building my dialog with just a json file and everything would be respected.

Lastly, I found that if I remove the `"checkboxstyle" : "switch,regular",` from the full json file, and instead call Dialog like this

```
/usr/local/bin/dialog --checkboxstyle "switch,regular" --jsonfile "/var/tmp/dialog.json"
```
I get the expected results and my dialog matches the first image above.

So it seems like it just doesn't like having **checkboxstyle** within the json _anywhere_. If I don't actually remove it from the json and call it like the line above, it reverts to the old style checkboxes, so it in fact has to be removed from the json for it to work.

Is there something I'm missing here, or is this a bug? Maybe the json parser is missing something that tells it how to interpret that new flag?

**Desktop (please complete the following information):**
 - macOS Monterey 12.6.5
 - swiftDialog version: 2.2.0.4426 Preview

**Additional context**
None

**Comment by bartreardon** [comment]
All good - exact type of stuff I want people reporting with this preview so thank you🙂

**Comment by bartreardon** [comment]
@mm2270 the correct syntax for checkbox style in json is the following:

```json
{
 "checkboxstyle" : {
    "style" : "switch",
    "size"  : "large"
  }
}  
  ```

Try that and let me know how it goes.

**Comment by mm2270** [comment]
@bartreardon Yep! That worked. Thanks!
