### ISSUE TITLE
Icon No rounded corners

### ISSUE THREAD

**Issue by bizzare** [bartreardon/swiftDialog#263]
There does not seem to be a way to have an icon that does not have rounded corners? I see nothing in the icon page about corner radius or anything that is customizable.

**Comment by acodega** [comment]
Icon in a dialog box, or the icon in the dock/notification center?

**Comment by bartreardon** [comment]
If you are talking about images displayed in the sidebar, then yes they have rounded edges as described in the wiki https://github.com/bartreardon/swiftDialog/wiki/Customising-the-Icon#basic-use. Corner radius is not a customisable setting.
