### ISSUE TITLE
Built-in Icons Fail to Load If Used as Overlay Icons

### ISSUE THREAD

**Issue by rougegoat** [bartreardon/swiftDialog#264]
**Describe the bug**
Built in icons do not load properly when used as overlayicons in 2.2.0

**To Reproduce**
Run `dialog --icon caution --overlayicon warning` or `dialog --icon warning --overlayicon caution`

**Expected behavior**
The built in icon will load properly as an overlay icon

**Screenshots**
![Screenshot 2023-05-24 at 3 11 40 PM](https://github.com/bartreardon/swiftDialog/assets/541022/91f93f74-4ab1-4687-9895-fdfcea9055d0)
![Screenshot 2023-05-24 at 3 12 42 PM](https://github.com/bartreardon/swiftDialog/assets/541022/c2f87a04-9062-4504-aff1-65e353629f75)

**Desktop (please complete the following information):**
 - macOS version 13.4
 - swiftDialog version 2.2.0.4535

**Additional context**

**Comment by bartreardon** [comment]
crap

**Comment by bartreardon** [comment]
LEt me know if [this release])https://github.com/bartreardon/swiftDialog/releases/tag/v2.2.1) fixes your issue.

**Comment by rougegoat** [comment]
I can confirm the 2.2.1 pre-release package resolved the issue.
