### ISSUE TITLE
Feature Request:  checkbox area modifications

### ISSUE THREAD

**Issue by Doronkerub** [bartreardon/swiftDialog#265]
The current state in 2.2 needs to be bigger for my use case.
It's working, and the new switches style is fantastic,
But I need to fill the screen with those checkboxes as much as possible for my use case. Therefore, I suggest adding `fill` to the `--checkboxstyle` option, and it should act like that:

The default behavior should be what's available now (that's what I'm trying to build):
<img width="700" alt="current state" src="https://github.com/bartreardon/swiftDialog/assets/112400624/d92adb89-c671-4c37-8675-14ef0bd2c7bf">

with `--checkboxstyle=switch,fill`:
<img width="700" alt="endgoal" src="https://github.com/bartreardon/swiftDialog/assets/112400624/1bfc05ff-63e7-4361-baa3-8924982b9bfd">

That change won't break anything for current deployments, but it will add versatility for other use cases.

**Comment by bartreardon** [comment]
you can already do this. Add `--messageposition top` and it will force all text to the top with no space between it and the next element

<img width="932" alt="image" src="https://github.com/bartreardon/swiftDialog/assets/3598965/4dd022b1-4393-45ba-97ae-2b331a358c95">

**Comment by Doronkerub** [comment]
Thanks! That works!
Unfortunately- doing so creates another bug:
![CleanShot 2023-05-31 at 12 02 19@2x](https://github.com/bartreardon/swiftDialog/assets/112400624/a0fb79ec-b147-4ea8-a8f7-85f4bd2a9953)

Should I open a different issue for you to track that?

**Comment by bartreardon** [comment]
Can i get you to test with the current preview release first? If you can replicate the issue with that version please include some demo code that causes the issue to happen.

**Comment by Doronkerub** [comment]
Sure, I've tested with the latest preview- the same issue.
I've uploaded A demo code that creates that issue:
[scroll_issue.sh.txt](https://github.com/bartreardon/swiftDialog/files/11611271/scroll_issue.sh.txt)

**Comment by bartreardon** [comment]
ok, seems to be an issue when `--bannerimage` is used it's messing with the geometry which in turn determines when the checkbox list is marked as scrollable or not.

In your code if you change the height value to something lower like `630` it renders fine, although that in turn makes the info box content overflow. Using a height of `750` ensures all the checkboxes are visible as well as the info box content. For the time being I suggest you use one of those values and adjust your content as required.

It is a bug though and an odd one at that.

**Comment by bartreardon** [comment]
Can you check this against the latest preview release and let me know how it looks for you. https://github.com/bartreardon/swiftDialog/releases/download/v2.3.0-validation-release-1/dialog-2.3.0-4703.pkg

**Comment by bartreardon** [comment]
fixed in [2.3](https://github.com/bartreardon/swiftDialog/releases/tag/v2.3.0)
