### ISSUE TITLE
User session unable to copy and paste from dialog screen

### ISSUE THREAD

**Issue by WardsParadox** [bartreardon/swiftDialog#266]
**Describe the bug**
If Outset (new or legacy) launches a script that creates a dialog when running as login privileged, users can not copy and paste.

**To Reproduce**
1. Create a login privileged every script that creates a dialog with copy paste able text
2. Attempt to copy, may succeed
3. Paste will always fail

**Expected behavior**
Because the dialog is opening in the user session, they should be able to copy and paste off the dialog

**Screenshots**
Can send screen recording via Slack as needed.

**Desktop (please complete the following information):**
 - macOS: 13.3, 13.4, 13.5 betas
 - swiftDialog : 2.2.0-4535

**Additional context**

**Comment by bartreardon** [comment]
> 1. Create a login privileged every script that creates a dialog with copy paste able text

Can you provide an example script that demonstrates what you mean here? just textfields or message text or something else?

**Comment by WardsParadox** [comment]
[Archive.zip](https://github.com/bartreardon/swiftDialog/files/11653531/Archive.zip)


Test runner and test config. Our script does a bit more processing that I can't currently share, but the part that is needed in included (run a json thats stored on the device as a json string). We run this via (python version for now) Outset's LoginPrivilagedEvery (again rest of the script does a bunch more processing so not to nag the user) so it ends up running as root to handle the other processing it needs.

**Comment by bartreardon** [comment]
Just trying your example with 2.2.0 and 2.2.1 and I can copy text out of the dialog in both cases with either select and cmd+c or select and right click+copy.

using macOS 13.4

**Comment by WardsParadox** [comment]
I'm still able to replicate this.

How are you launching the script? If you launch it via terminal and using `outset` itself, it works. If you kickstart it with `launchctl` it fails.

**Comment by bartreardon** [comment]
Right. I've been able to replicated it now. What you're seeing is likely an issue with how outset does what it does in the launchd environment and how `/usr/local/bin/dialog` tries to ensure the actual app runs in the user context which is important for adhering to language and UI colour preferences etc. For this deeper level of execution you're probably better off running the app bundle directly.

in your test script, replace lines 8-10 with:

```
dialog = "/Library/Application Support/Dialog/Dialog.app"

dialog_cmd = ["open", dialog, "--args", "--jsonstring", json.dumps(config)]
```

If you want to capture user input (since `open` will launch the app and return execution to the calling script immedietly) then use this instead:

```
dialog = "/Library/Application Support/Dialog/Dialog.app/Contents/MacOS/Dialog"

dialog_cmd = [dialog, "--jsonstring", json.dumps(config)]
```

**Comment by WardsParadox** [comment]
Will give the at a shot first thing in the morning!

Didn’t think about that.

**Comment by WardsParadox** [comment]
So swapping either or results in:
1. (Using Open), --args is not properly passing to the open command and just immediately closes the terminal, doesn't pass in the jsonstring arg
2. (Using direct binary call) results in same behavior.

**Comment by bartreardon** [comment]
hmm - odd. Using either here results in being able to copy text from the dialog window when launched via outset. I'm running that by touching the trigger file (which if you're on outset 3 would be `/private/tmp/.com.github.outset.login-privileged.launchd`)

**Comment by bartreardon** [comment]
It's defiantly a launch environment issue though, not specifically a swiftDialog issue.

**Comment by bartreardon** [comment]
can you check out the latest preview build and LMKWYT https://github.com/bartreardon/swiftDialog/releases/download/v2.3.0-validation-release-1/dialog-2.3.0-4703.pkg

There is a known behaviour where you can only select text from one paragraph/sentence/item thing. This is a limitation of SwiftUI and how MarkdownUI splits components into seperate views. I consider this a minor inconvenience compared to the benefits of better markdown support but want to make sure the ability to select and copy text still fits your use case.

**Comment by WardsParadox** [comment]
Testing today

**Comment by WardsParadox** [comment]
As of 2.3.0 release, Dialog no longer displays the window with the same script + json attached here already.

**Comment by bartreardon** [comment]
working here on Ventura and swiftdilaog 2.3.0.4706

<img width="1025" alt="image" src="https://github.com/bartreardon/swiftDialog/assets/3598965/ecf83f38-2198-4df1-9bb0-068bd5f5e637">

A couple of changes I had to make though:
 - whatever you have set up for managed python I don't have so I'm using the system `/usr/bin/python3` (whatever comes with Xcode)
 - Outset isn't a fan of having `test.json` in the same folder as the script as it's not a file that can be processed. I created a `/usr/local/outset/support-files` directory, moved `test.json` to there and then set the path in the script to that location. 

Triggering login-every-privileged with `touch /private/tmp/.io.macadmins.outset.login-privileged.launchd` launches the dialog and I can select text (with the caveat of my previous comment on selecting text that crosses multiple SwiftUI views)

**Comment by bartreardon** [comment]
right - gotcha.

Try this - in `/usr/local/bin/dialog` change[ line 26](https://github.com/bartreardon/swiftDialog/blob/4b1cba336386bce354fb23bdd23207a4ce115eb1/dialog/Package/pkgroot/usr/local/bin/dialog#L26) to the following:

```bash
launchctl asuser $(id -u $currentUser) "$dialogbin" "$@"
```

**Comment by WardsParadox** [comment]
Going to give that a shot and test.

**Comment by WardsParadox** [comment]
This seems to work as expected now!

Not been able to replicate the failure since.

**Comment by bartreardon** [comment]
nice - yeah `launchctl as user` is much better for user context. If only [someone had written a blog post](https://breardon.home.blog/2019/09/18/sudo-u-vs-launchctl-asuser/) on the subject.

I've updated that line so will be included in the next beta release
