### ISSUE TITLE
`--mini` options seems to be broken

### ISSUE THREAD

**Issue by Theile** [bartreardon/swiftDialog#267]
**Describe the bug**
Nothing is shown or returned from dialog if I use `--mini` option.

**To Reproduce**
Run this command (as root):
`open -a "/Library/Application Support/Dialog/Dialog.app" --args --mini`
or
`/usr/local/bin/dialog --mini`
And nothing happens!

I have to go back to version 2.0.1 to get the window to show up.

**Expected behavior**
Mini window shown

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: Ventura 13.4
 - swiftDialog version

**Comment by joncrain** [comment]
No issues here on 2.2.0.4535 (13.4 OS)

**Comment by Theile** [comment]
I just tested again. If run as root, as our Installomator scripts are from Jamf Pro, it does not show up.

**Comment by bartreardon** [comment]
closing this as a non issue
