### ISSUE TITLE
Setting Icon to none disables infobox

### ISSUE THREAD

**Issue by drtaru** [bartreardon/swiftDialog#272]
**Describe the bug**
If the Icon parameter is set to "none" the infobox sidebar does not render 
Currently the workaround is to set a transparent png as the icon and set the iconsize to "1" but this seems less than ideal.
Screenshots Provided

**Screenshots with code examples**

```
"infobox" : "TEST Infobox",
"icon" : "none",
```
<img width="932" alt="image" src="https://github.com/bartreardon/swiftDialog/assets/1212524/870a3a51-a6db-458b-ab98-9512baeedec4">

```
"infobox" : "TEST Infobox",
"icon" : "https://upload.wikimedia.org/wikipedia/commons/c/ca/1x1.png",
"iconsize" : "1",
```
<img width="932" alt="image" src="https://github.com/bartreardon/swiftDialog/assets/1212524/af004e1c-bad1-45ab-a482-c826cd6227c1">

**Comment by bartreardon** [comment]
fixed in [2.3](https://github.com/bartreardon/swiftDialog/releases/tag/v2.3.0)
