### ISSUE TITLE
Allow the fileselect option choose directories and/orfiles

### ISSUE THREAD

**Issue by ScottEKendall** [bartreardon/swiftDialog#273]
The --textfield "Select a file,fileselect" option is wonderful to pick individual files, but would it possible to allow it to also choose Directories as well?  maybe do a **--textfield "Select a file,dirselect"** in addition to the **--textfield "Select a file,fileselect"** option

**Comment by bartreardon** [comment]
yup - this is already implemented in the 2.3 dev branch https://github.com/bartreardon/swiftDialog/blob/b0bfec257eda3264f82740583fdd14ce60270475/dialog/UI/TextEntryView.swift#L71

**Comment by bartreardon** [comment]
implemented in [2.3](https://github.com/bartreardon/swiftDialog/releases/tag/v2.3.0)
