### ISSUE TITLE
Wiki Sidebar incorrect link for "Provide list of selectable items"

### ISSUE THREAD

**Issue by Macjutsu** [bartreardon/swiftDialog#275]
In the Wiki _Sidebar.md this link is incorrect:

`[Provide list of selectable items](https://github.com/bartreardon/swiftDialog/wiki/Selectable-Lists)`

Should it perhaps go here instead?

`[Provide list of selectable items](https://github.com/bartreardon/swiftDialog/wiki/Select-Lists-and-Radio-Buttons)`

**Comment by bradtchapman** [comment]
Also reporting this issue. 

The sidebar links to "https://github.com/bartreardon/swiftDialog/wiki/Selectable-Lists"

But when you try to access this page it says "You do not have permission to edit this wiki."

I'm ... not trying to do that?

**Comment by bradtchapman** [comment]
@bartreardon save us!

**Comment by bradtchapman** [comment]
Also, I can **search** the repository for the page and it appears in the results, but when I click it, GitHub redirects back to the main page.

**Comment by bartreardon** [comment]
oh yeah - I changed the page name so it was clearer that select lists and radio buttons are the same thing just with a different view type

fixed up now
