### ISSUE TITLE
NO message

### ISSUE THREAD

**Issue by nlecchi** [bartreardon/swiftDialog#276]
**Describe the bug**
I haven't any message on my screen

**To Reproduce**
from terminal run:
sudo /usr/local/bin/dialog --title HELLO 
or any other dialog command

**Expected behavior**
Dialog Message with title HELLO

**Desktop (please complete the following information):**
 - macOS version: VENTURA 13.4.1
 - swiftDialog version: dialog-2.2.1-4591

**Comment by bradtchapman** [comment]
What is your current "do not disturb" or "focus" setting on the Mac?  Does swiftDialog run if you disable it ?

**Comment by nlecchi** [comment]
Focus not enable

**Comment by nlecchi** [comment]
is there a secure way to complete remove swiftDialog?

**Comment by nlecchi** [comment]
I have the same problem with a fresh new administrator user

**Comment by nlecchi** [comment]
I solved by uninstalling all the files and also dialog.log.
Reinstalled now works fine?

**Comment by BigMacAdmin** [comment]
Occasionally you can get a lingering ‘quit:’ command in your dialog.log file, which new windows read and immediately quit.

**Comment by nlecchi** [comment]
In fact, I solved it by deleting the dialog.log
