### ISSUE TITLE
Increase line spacing of text in the message area

### ISSUE THREAD

**Issue by bradtchapman** [bartreardon/swiftDialog#278]
**Why are you requesting this feature?**
The line spacing in the Message area is too compact for adequate legibility.  Apple's page of "UI Design Do's and Dont's" strongly encourages developers to slightly expand line spacing for better readability: https://developer.apple.com/design/tips/

**Describe what you want the feature to do:**: Please increase the default spacing of the message area to 1.3 lines, or offer administrators a way to configure it in the `--messagefont` options.  FYI, Apple's standard is 1.3 line spacing across the operating system and in their marketing materials.

Some font families include more or less internal line spacing than others.  Without specifying a font family, swiftDialog will use "SF Pro Text" from Apple.

As a side benefit, I found that increasing the line spacing also enables the "Live Text" detection when taking a screenshot of SwiftDialog.  When the line spacing is too compact, it doesn't see any text.

**Describe workarounds, if any:**
The only present alternate is to add a newline \n character after every line, but this adds too much empty space.  It would also cause serious text flow issues if the admin decides to resize or adjust the dialog box later.

**Any screenshots or recordings?**
Why, I'm glad you asked!  Here are two "screenshots" of swiftDialog that were mocked up in Photoshop to recreate the problem and set different amounts of line spacing.  

Line spacing ratio = line leading (points) ÷ font size (points)

FYI swiftDialog's default line spacing is calculated at ~ **1.03 lines**. (17.6 pt leading ÷ 16 pt font size)

---

## Text ~1.03 Line Spacing:

![swiftdialog-linespacing-1 03](https://github.com/bartreardon/swiftDialog/assets/32527656/e3b391e1-e4d8-41c9-8d2c-91bfca6b1974)

## Text @ ~1.35 Line Spacing:

![swiftdialog-linespacing-1 35](https://github.com/bartreardon/swiftDialog/assets/32527656/adba2b96-4be0-4828-95d8-1dcaebdd8494)

---

## Bonus: Live Text detection
Here we see that in QuickLook, the Live Text framework **only** activates on the screenshot with the greater line spacing.

![swiftdialog-livetext-detection](https://github.com/bartreardon/swiftDialog/assets/32527656/9ae3aa12-cb4f-4f7d-93be-0c1b9b55d12f)

**Comment by bradtchapman** [comment]
FYI one text property for line spacing in SwiftUI is [Font.Leading](https://developer.apple.com/documentation/swiftui/font/leading).  The equivalent in ObjectiveC is [lineHeightMultiple](https://developer.apple.com/documentation/uikit/nsparagraphstyle/1528614-lineheightmultiple/).  It doesn't appear that SwiftUI offers exact control over leading size; you get "standard, loose, tight" and that's it.

**Comment by bartreardon** [comment]
I don't see the issue with screenshots not being picked up for live text but a decent change nontheless. A good opportunity to do it as well since message formatting is getting a decent update in 2.3 (and causing me pain but that's progress for you)

**Comment by bartreardon** [comment]
something like this?

<img width="932" alt="image" src="https://github.com/bartreardon/swiftDialog/assets/3598965/cc82cb1c-24ff-45a3-92a3-8209e63c9d7c">

**Comment by bradtchapman** [comment]
Yes.  👏  Looks very nice.  Thanks!

**Comment by bartreardon** [comment]
fixed in [2.3](https://github.com/bartreardon/swiftDialog/releases/tag/v2.3.0)

**Comment by bradtchapman** [comment]
🎉🎉🎉
