### ISSUE TITLE
Minor button enhancments

### ISSUE THREAD

**Issue by jalucia** [bartreardon/swiftDialog#284]
**Is your feature request related to a problem? Please describe.**
No, purely cosmetic.  I'd love to see some minor enhancements to buttons.

**Describe the solution you'd like**

- The ability to completely hide Button1, not just deactivate it.
- The ability to center Button1 or Button2 since that one is closer to center of the Dialog window.  

**Describe alternatives you've considered**

DEP Notify

**Additional context**
Attached two DEP Notify screens.  One shows a window without buttons and the other shows the buttons centered.
<img width="1440" alt="Screenshot 2023-07-05 at 2 06 32 PM" src="https://github.com/bartreardon/swiftDialog/assets/38197515/a81b760a-52df-437d-a88e-aafc46fcc078">
<img width="1440" alt="Setup" src="https://github.com/bartreardon/swiftDialog/assets/38197515/c9633797-f70c-43c7-a9ee-0a7c12145ca6">

**Comment by bartreardon** [comment]
> The ability to center Button1 or Button2 since that one is closer to center of the Dialog window.

This is a good idea and I've added it in.

> The ability to completely hide Button1, not just deactivate it.

This has been requested a few times. Despite it being used in onboarding workflows as a depnotify replacement, the primary purpose for swiftDialog is user dialogs, notifications and the like. I'm particularly hesitent offering a view that gives no indication how to quit or continue if the process behind it stops working.

**Comment by bartreardon** [comment]
Resolved in [v2.3](https://github.com/bartreardon/swiftDialog/releases/tag/v2.3.0)

(including hiding button 1 - see release notes for more info, wiki is yet to be updated)
