### ISSUE TITLE
Swiftdialog Menu Bar 

### ISSUE THREAD

**Issue by mani2care** [bartreardon/swiftDialog#290]
Here the some examples how was working some other concepts here I’m looking for swiftdialog how to enable the menu bar with status example for 

https://github.com/swiftbar/SwiftBar
https://github.com/jeremybessard/sumb

**Comment by bartreardon** [comment]
Thanks for the suggestion but this isn't the type of thing swiftDialog is aimed at doing. For menu bar stuff I can highly recommend [Support App](https://github.com/root3nl/SupportApp)
