### ISSUE TITLE
Progress bar missing when dialog is set to center

### ISSUE THREAD

**Issue by donmontalvo** [bartreardon/swiftDialog#294]
**Describe the bug**
if we leave the dialog box set to “bottomright”, the default, we see a progress bar. If we set the dialog box to center, there is no progress bar.

**To Reproduce**
1. Leave “—position” set to default “bottomright”.
2. Run the script, see progress bar, percentage, and dialog box goes away when Finder opens.
3. Set “—position” to “center”
4. Run the script, no progress bar, no percentage, and dialog box does not go away when Finder window opens.

**Expected behavior**
Progress bar should show when “—position” is set to “center”.

**Screenshots**
Our firewall prevents screenshot upload.

**Desktop (please complete the following information):**
 - macOS Ventura (13.5)
 - swiftDialog 2.2.0.4535

**Additional context**

**Comment by bartreardon** [comment]
Hi, I'm not sure what you are reporting. Are you able to provide some sample code that demonstrates what you are experiencing?

Some reasons for my confusion:

 > if we leave the dialog box set to “bottomright”, the default, we see a progress bar.

`bottomright` isn't the default position for dialog, center is (actually slightly up from centre)

 > Run the script

I'm not sure what script you are referring to. swiftDialog doesn't come with any scripts.

 > swiftDialog 2.2.0.4535

Can you test with the latest version (2.3) or at least the prior version (2.2.1)?

if I run `dialog --progress --position center` it works as I expect. It sounds like what you are experiencing is an issue with whatever script you are running but I don't have any insight into what that is so unfortunately I can't give any advice.

**Comment by donmontalvo** [comment]
It is a script, my apologies, I’ll reach out to the author.
