### ISSUE TITLE
FR: New type of textfield (ability to mask input with asterisk or similar)

### ISSUE THREAD

**Issue by fortiko** [bartreardon/swiftDialog#87]
Thank you for a great project, it is really hard to find though!

I was surprised that there was no way for now to specify the "masking" character (usually asterisk *) for a text input field. Is that something you would consider?

Cheers!

PS: I also like the background feature, very similar to DEPnotify and can potentially replace it.

**Comment by bartreardon** [comment]
Excellent suggestion 🙂 - I'm actually working on that exact feature for 1.10.

Adding a password field in itself is not an issue. There's seems to be a bug in xcode though with the way I would like to implement it (by passing in `--textfield password`) in that it will work for a password field _or_ a textfield but not both for some reason - the compiler craps out.

Once I sort that out though, password fields will be a thing 🙂. It may be that it becomes a seperate type and not a special type of textfield. We'll see.

**Comment by bartreardon** [comment]
Implemented in 1.10 🙂
