### ISSUE TITLE
FR: Allow swiftDialog window size to be updated after launch

### ISSUE THREAD

**Issue by smithjw** [bartreardon/swiftDialog#92]
As a Mac Admin, I want the ability to resize a `swiftDialog` window after launch so that it can conform to the content displayed

**Comment by bartreardon** [comment]
@smithjw can you check this feature in v2.0 preview? command file `width: ` and `height: ` commands should adjust window size and respect window positioning

**Comment by bartreardon** [comment]
Fixed in 2.0
pass `width: <num>` or `height: <num>` to the command file 🙂
