### ISSUE TITLE
default text in textfield

### ISSUE THREAD

**Issue by shannonpasto** [bartreardon/swiftDialog#93]
Great project. I have a suggestion...

When using `--textfield` it'd be great to be able to specify some default text so it appears in the field "pre-filled", perhaps slightly greyed out but not a big issue if it can't be. If no text is added then it can use the default text in the output.

Cheers,
Shannon

**Comment by bartreardon** [comment]
Good suggestion - will add to the 1.10 release

The ability to have a prompt oddly enough didn't appear until macOS 12 - so this will be available when running under macOS 12 but not 11

Will be ignored on secure fields.

### command line argument 

`--textfield "Name",required,prompt="Enter your name here"`

### json

```json
{
  "textfield" : [
    {"title" : "Name", "required" : true, "prompt" : "Enter your name here"}
  ]
}
```

![image](https://user-images.githubusercontent.com/3598965/159401448-afd6e531-6d8e-4d30-938d-422aab7b7209.png)

**Comment by bartreardon** [comment]
Merged and closed
